### ISSUE TITLE
Dispatch refresh fails with 401 error with newly assigned subscription key

### ISSUE THREAD

**Issue by angie4u** [microsoft/botbuilder-tools#1081]
## Tool
Name: Dispatch
Version: *1.3.0*
OS: *1809*

## Describe the bug
https://stackoverflow.com/questions/55124676/azure-bot-builder-dispatch-refresh-fails-with-401-error 
As this describes, we cannot update our dispatch model with newly assigned LUIS key. When I want to update dispatch model, I need to change temporarily with original authoring key -> refresh dispatch model -> change again to use paid subscription key 

## To Reproduce
1. Refresh dispatch model with a standard subscription key
2. You will get this error.
```
"statusCode": 401, "message": "Access denied due to invalid subscription key~~
```

## Expected behavior
Refresh dispatch should work.

## Additional context

[bug]

**Comment by tsuwandy** [comment]
@angie4u , this is by design at the moment.  

There are two different keys being used to use Dispatch CLI tool. Authoring key and subscription key. Authoring key is the key from luis.ai portal and needed to export the LUIS sources for Dispatch and to upload the newly created Dispatch app to luis portal. Subscription key is optional and is used for hitting luis endpoint/prediction API. If subscription key (created from Azure portal for LUIS Cognitive Service) is put in place of authoring key, Dispatch CLI won't be able to create and upload/refresh Dispatch app into luis. 

Subscription key from Azure can't be used as authoring key (used to import Dispatch app into luis).  

There's on going work to combine keys so user will only have to deal with one key, I don't have an ETA for this work, it should be sometime this year.
