### ISSUE TITLE
Dispatch refresh results in new dispatch model

### ISSUE THREAD

**Issue by matthew-clark02** [microsoft/botbuilder-tools#1106]
## Tool
Name: Dispatch
Version: 1.3
OS: Mac 10.14.3

## Describe the bug
When calling `dispatch refresh` using a .dispatch file for a model that already exists a new model is created instead. This happens when the authoring key used is that of a collaborator on the original dispatch model instead of the creator.

The result is the owner of the authoring key is removed as a collaborator from the original model and an entirely new model is created with the same name. The original model remains unchanged.

## To Reproduce
1. Create the dispatch model 'dispatch-test' with user A
2. Add User B as a collaborator to dispatch model 'dispatch-test'
3. Create a .dispatch file with the name 'dispatch-test'.
4. Run `dispatch refresh` on the dispatch file using User B's authoring key.
4. User B is removed as a collaborator on the original 'dispatch-test' model and an entirely new 'dispatch-test' dispatch model has been created with User B as the owner.

## Expected behavior
Calling `dispatch refresh` should update the existing model rather than create a new one.

## Additional context
I think this results from a lack of application id being provided to the CLI. The result is the only identifier is the name and rather than using the model which exists with that name but owned by a different user, it creates a new model.

[bug]

**Comment by tsuwandy** [comment]
Trying to repro...

**Comment by tsuwandy** [comment]
@matthew-clark02 I can't repro this.  Created a dispatch app, add a collaborator, then replace the authoring key in the .dispatch file (authoring key for Dispatch, not the keys under services array) to the collaborator authoring key and the dispatch is updated.  

Did you get an error?  As long as the .dispatch file (with everything populated from the "create" command) is in the same place as where the refresh command is run, the dispatch app will be refreshed/updated.

Otherwise the "refresh" command behaves like a "create" command.

**Comment by tsuwandy** [comment]
@matthew-clark02, please let us know if issue still persists for you as I couldn't repro it (see my previous comment).
