### ISSUE TITLE
Better .bot file documentation

### ISSUE THREAD

**Issue by MCKRUZ** [microsoft/botbuilder-tools#1155]
## Tool
.Bot file

## Describe the problem
There needs to be better documentation on what the .bot file can read, for example you make reference to the fact that it can connect to Azure blob storage...but there is no example of that anywhere.  I have no idea what parameters to use and where to place it.  There should be a clear example of everything you can do with the .bot file somewhere.

I have looked at this example (https://github.com/microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/sample-bot-file.json)
but it doesn't cover every scenario.

## Describe the solution you'd like
I would like an example of every parameter that the .bot file can read

[enhancement]

**Comment by mdrichardson** [comment]
The `.bot` file has been deprecated. You can use [this resource](https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp) to help you migrate away from the `.bot` file.

Specifically for Azure Blob Storage, you can use these for guidance:

* [C#-Scaleout Sample](https://github.com/microsoft/BotBuilder-Samples/blob/3cfb7eec6a11f653203781c652245a6288d6286e/samples/csharp_dotnetcore/42.scaleout/BlobStore.cs#L18)
* [Implement Custom Storage](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#implementation-1) - scroll down to `BlobStore.cs`
* [Write Directly to Storage](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#implementation-1)

That being said, if you'd like to see all of the settings that are available, you can look at the properties used in:

* [`Microsoft.Bot.Configuration` - C#](https://github.com/microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Configuration/Services). Look at the `JsonProperty`s

* [`botframework-config` - Node](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botframework-config/src/models). Look at the class properties.

I'm going to close this issue as this enhancement won't be pursued due to `.bot` file deprecation. If you have trouble implementing any of this, please post on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework)

**Comment by MCKRUZ** [comment]
Doesn’t the bot file still get used for the emulator?  That’s what I’m referring to.

**Comment by mdrichardson** [comment]
The bot file *can* still get used by the emulator, but the convention now is to use the Open Bot dialog in Emulator. I sometimes use a bot file just to keep the endpoints saved as it makes loading the bot in the Emulator easier. However, api keys should be stored in `appsettings.json`/`.env`
