### ISSUE TITLE
enterprise bot template (C#) app deployment fails

### ISSUE THREAD

**Issue by PurnaChandraPanda** [microsoft/botbuilder-tools#1156]
We have bot applications based on "Enterprise Bot Template". It's been developed and deployed using "msbot" CLI options. As per the recent changes, "msbot" seems to be deprecated. Upon trying the "msbot clone services" command, it failed at the steps of "az bot create". With the “msbot clone services” tried out, just had app service and app service plan created, but not bot or any other resources.

..az login
..account set for correct subscription
..msbot clone services

```diff
PS C:\Users\user\Desktop\testKeyva\NttData.PA.Chatbot.PoC\NttData.PA.Chatbot.PoC>msbot clone services --name "kevyabotpurna1" --luisAuthoringKey "luis-auth-id" --folder "DeploymentScripts\msbotClone" --location "westus" --appId "az-app-id" --appSecret "az-app-secret"
..
Checking az botservice version
checking dotnet requirement
Fetching subscription account
The following services will be created by this operation:
Service                                 Location            SKU                 Resource Group
Azure App Site Plan                     westus              S1                  kevyabotpurna1
Azure AppInsights Service               West US 2           F0                  kevyabotpurna1
Azure Blob Storage Service              westus              Standard_LRS        kevyabotpurna1
Azure Bot Service Registration          Global                                  kevyabotpurna1
Azure CosmosDB Service                  westus              1 write region      kevyabotpurna1
Azure LUIS Cognitive Service            westus              S0                  kevyabotpurna1
Azure LUIS Cognitive Service            westus              S0                  kevyabotpurna1
(Dispatch)
Azure QnA Maker Service                 westus              S0                  kevyabotpurna1
Azure Search Service                    westus              basic               kevyabotpurna1
Azure WebApp Service (Bot)              westus                                  kevyabotpurna1
Azure WebApp Service (QnA)              westus                                  kevyabotpurna1
Resources will be created in subscription: Microsoft Azure (`subscription-id`)
Would you like to perform this operation? [y/n]y
Creating Azure group [kevyabotpurna1]
Using the provided ApplicationId and Secret rather than auto-provisioning
Creating Azure Bot Service [kevyabotpurna1]
+ az bot create -g kevyabotpurna1 --name kevyabotpurna1 --kind webapp --location westus --insights-location "West US 2" --subscription subscription-id --version v4 --lang CSharp --appid az-app-id -p "az-app-secret" exit code: 1
+ WARNING: WARNING: `az bot create` for v4 bots no longer creates or uses Application Insights. If you wish to create Application Insights via Azure CLI, please use an ARM template.

++ ERROR: Deployment failed. Correlation ID: 67701900-faab-41f0-ae76-d1c96a8cef01. {
++   "error": {
++    "code": "InvalidBotData",
++    "message": "Bot is not valid. Errors: Id: Id is already in use.. "
++  }
++ }
```
## Request
I understand the recommendation is to upgrade the enterprise template based app to virtual assistant. Is that the only route that customer have to take? If yes, it would involve dev effort to bring in custom code/ configuration changes to “virtual assistant”. Can somehow customers continue with “msbot clone services” CLI? If we have any general guidance in terms of configuration or deployment, that is customer ready, for “msbot” consumers, it would be really nice. Any definite answer over what existing “enterprise bot” customers do moving forward, would be helpful!

**Comment by sgellock** [comment]
@mailforsachin thank you for opening the issue.  starting with the 4.3 release of the Bot Framework SDK we have made significant investments in supporting existing Azure resource provisioning and deployment mechanisms.  Specifically ARM templates for resource provisioning, and Azure-CLI for provisioning and deployments.  as such, msbot, which had a minor subset of Azure-CLI functionality, is being deprecated.  

I'll leave this issue open so our support team can help with your transition to ARM.

**Comment by CoHealer** [comment]
@jwiley84 , please assist @mailforsachin in transitioning to ARM

**Comment by jwiley84** [comment]
Just as an aside, I'm running into ARM deployments of my own. As soon as I get them solved, I'll ping here.

**Comment by mailforsachin** [comment]
Guys, let me know if you have an update yet.

**Comment by mailforsachin** [comment]
Hi @jwiley84, please let me know if you have an update.

**Comment by jwiley84** [comment]
Hi @mailforsachin!

Sorry for the massive delay, I hit some major hiccups of my own when trying to deploy via ARM. First question: are you proficient with powershell? The simpler version of deploying a VA/Enterprise  bot with powershell, though very much possible to simply use windows command line as well.

**Comment by mailforsachin** [comment]
Yes, please. I am able to push the code using the deploy strategy of the new template. 

But we need to push an existing Enterprise template code . Here is what I have done.

I copied the deployment scripts to my existent code and when I execute, I get the following message

PS C:\Users\124708\Desktop\intermediator-bot-sample\ibs> .\Deployment\Scripts\deploy.ps1
? Bot Name (used as default name for resource group and deployed resources): handoff
? Azure resource group region: westus
? Password for MSA app registration (must be at least 16 characters long, contain at least 1 special character, and contain at least 1 numeric character): aabbcfgg!!
? LUIS Authoring Region (westus, westeurope, or australiaeast): westus
? LUIS Authoring Key (found at https://luis.ai/user/settings): 0a349198fce3cb65004779e
> Creating resource group ...
> Validating Azure deployment ...
! Template is not valid with provided parameters.
! Error: The template deployment 'deployment_dry_run' is not valid according to the validation procedure. The tracking id is '420c501d-1399-44d1-b6a8-776ebf8f3'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.

Earlier it was as simple as this

npm install -g ludown luis-apis qnamaker botdispatch msbot chatdown
dotnet tool install -g luisgen
az login
az account set --subscription "xxx"

PS C:\Users\124708\source\repos\ServiceKeyBOT\ServiceKeyBOT> msbot clone services --name "UNIQUE BOT NAME" --luisAuthoringKey "kdkdne"
 --folder "DeploymentScripts\en" --location "westus" --appId "07e62e18-51d-af-992a-dc2c1d3fceff" --appSecret "xoekCdfdfFYYW57-{"

I would like to understand

a) How to use the erstwhile enterprise bot template to push code to a new azure tenant?
b) How to publish the EB template code ?

If I breakdown the process per the new template, it is to 
a) Create app id and resource group

(az ad app create `
		--display-name $name `
		--password $appPassword `
		--available-to-other-tenants `
		--reply-urls 'https://token.botframework.com/.auth/web/redirect')


(az group create --name $resourceGroup --location $location) 2>> $logFile | Out-Null

b) az group deployment validate `
		--resource-group $resourcegroup `
		--template-file "$(Join-Path $PSScriptRoot '..' 'Resources' 'template.json')" `
		--parameters "@$($parametersFile)" `
		--parameters name=$name microsoftAppId=$appId microsoftAppPassword="`"$($appPassword)`""

where parametersfile is json file inside template.json

and then create

c)
az group deployment create `
				--name $timestamp `
				--resource-group $resourceGroup `
				--template-file "$(Join-Path $PSScriptRoot '..' 'Resources' 'template.json')" `
				--parameters name=$name microsoftAppId=$appId microsoftAppPassword="`"$($appPassword)`""

if the create deployment succeeds then update appsettings.json file and then publish the cognitive models  and publish the bot

**Comment by jwiley84** [comment]
Your process there (Steps A, B, C) all look to good to me, which is why the error you're getting on the validate step is so strange. I don't commonly do validations prior to deployment, but I know that is not the norm. 

Try logging into the portal, navigating over to the resource group, and checking the activity logs: 
![image](https://user-images.githubusercontent.com/17333688/59296608-3adc8380-8c3b-11e9-86a8-b0c5e64a5127.png)

Look for the operation with the name 'Validate'. To make it easier, you can select 'event severity' from the top filter and uncheck 'informational', since we're looking for a failure. There should be a message that says why the validation failed there.

**Comment by mailforsachin** [comment]
@jwiley84 

Could you explain?

a) How to use the erstwhile enterprise bot template to push code to a new azure tenant, pushing the same code?
b) How to publish the EB template code, using the same technique ?

**Comment by jwiley84** [comment]
Of course!

To deploy and publish, using an ARM template on an Enterprise bot, you're going to take the steps you outlined above: 

**a)** `az ad app create --display-name <ENTERPRISE_BOT_NAME> --password "1234567890ABCDEF" --available-to-other-tenants` Make sure you write down the 'AppId' that will come up in the JSON upon success.

**b)** `az group create --name <ENTERPRISE_RESOURCEGROUP_NAME> --location <REGION>`

**c)** Create your template.json The one from the VA bot (which i've posted below) will function for this very well, as the enterprise bot was the precursor to the VA bot and they have a lot of the same functionality. Create a folder called 'Resources' inside your 'Deployment' folder, then create a template.json file. Then copy and paste the code below and save the file. 

**d)** `az group deployment create --name <ENTERPRISE_BOT_NAME> --resource-group <ENTERPRISE_RESOURCEGROUP_NAME> --template-file "./Deployment/Resources/template.json"`

to PUBLISH the bot, you're going to add a couple more commands:

**e)** `az bot prepare-deploy --lang Csharp --code-dir "." --proj-file-path "<YOURBOTNAME>.csproj"`

The Bot Framework deployment docs mention one specific thing here: 

> You must provide the path to the .csproj file relative to --code-dir.

Because I was running all these commands from the main folder of my project, I only needed "." This command will create a ".deployment" file, and you can proceed to the next step

**f)** Zip/Compress your files. I used Windows embedded 'compress' option. You must compress the files at the level I have shown in the pic below. Do not step up to a root folder. Once you have it, name the zip file 'code.zip'.

![image](https://user-images.githubusercontent.com/17333688/59369609-a125dc80-8cf5-11e9-80e7-21b5cfbb8013.png)

**g)** Run `az webapp deployment source config-zip --resource-group <ENTERPRISE_RESOURCEGROUP_NAME> --name <ENTERPRISE_BOT_NAME> --src "code.zip"`


As I said before, you were very much on the right track for deploying your Enterprise bot. If you get an errors on any of these steps, please let me know.

**Comment by jwiley84** [comment]
Hi @mailforsachin @PurnaChandraPanda 

I'm going to close this, as I assume the above steps solved your issues. If it did not, please email me at v-jewail@microsoft.com and I'll reopen it.
