### ISSUE TITLE
Why is Kudu build advised over uploading prebuilt binaries?

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botbuilder-tools#1162]
(Not sure whether this should be a docs issue or a botbuilder-tools issue. Also asked at https://github.com/MicrosoftDocs/bot-docs/issues/1169)

It looks like the Bot Framework suggests letting App Service build the bot logic from source using Kudu (using `az bot prepare-deploy` + `az webapp deployment source config-zip`) rather than have the user / CICD upload prebuilt binaries.

Personally I thought the idea of CI/CD was making one deployment package containing binaries that can be configured using appsettings.json. This deployment package could then be distributed to various environments. I wonder why the Bot Framework deviates from this - it is just an ASP.Net Core web app, after all.

This non-standard choice for deployment package creation and the usage of the bot file to store secrets rather than using appsettings + environment variables make this feel a bit uneasy / awkward to me.

Could you please explain why the bot framework seems to deviate from the ASP.Net Core standards, what the benefits of it are and why we should stick to it?

**Comment by stevengum** [comment]
The steps outlined under the [**"Deploy your bot"**](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg) article are for a quick-start method to get a local bot deployed to Azure. 

> " ... it is just an ASP.Net Core web app, after all."

This is correct. There's nothing inherently special about deploying a bot. 

For advanced users who already have their own CI/CD pipelines setup, we don't advocate using Kudu over that. Every user will have a different set of requirements for deploying their bots in production,  Kudu's zipdeploy method is one of the more simpler methods of deploying code to Azure App Services.

`az bot prepare-deploy` actually just creates files necessary for deploying an app on Azure App Services. (A `web.config` for Node.js, and a `.deployment` file for C#).  

This command could (theoretically) be used outside of the Microsoft Bot Framework context, but would still be applicable to deploying C# or Node.js apps to Azure.

### Bot files:

> "This non-standard choice for deployment package creation and the usage of the bot file to store secrets rather than using appsettings + environment variables make this feel a bit uneasy / awkward to me."

As mentioned in the other issue, we deprecated the use of bot files and do not recommend using them. The ARM templates in the samples actually configure the MicrosoftAppId and MicrosoftAppPassword _on the App Service (Application Settings/Configuration)_ so that when the bot is deployed to Azure it can automatically work with the Bot Framework Channel Service. When debugging locally, the user should not have to use the credentials unless they are used locally by the bot.

**Comment by sgellock** [comment]
Given the feedback from the team and no additional customer feedback, I'm closing this issue.
