### ISSUE TITLE
luisgen: list entities parsed into a 2d array of strings 

### ISSUE THREAD

**Issue by litofish** [microsoft/botbuilder-tools#1231]
## Tool
Name: LuisGen

## Describe the problem
Why are list entities parsed into a 2d array of strings rather than a 1d array? It seems like it could make sense to have a 2d array if it contained both the entity from the utterance and the value it was resolved to, but right now it seems to just give the resolved value.

![parsed_result](https://user-images.githubusercontent.com/39777667/62087216-d3dc5380-b215-11e9-82fe-50c526004655.PNG)
![recognizer_result](https://user-images.githubusercontent.com/39777667/62087612-34b85b80-b217-11e9-8ffe-840a9e4e257e.PNG)

**Comment by chrimc62** [comment]
All entities in LUIS come back as arrays because a sentence can include more than one instance of an entity--that is why there is a separate entity for "shampoo" and "conditioner".  For list entities the second level is because the resolution can be ambiguous.  Imagine you have "green peppers" with a synonym of "peppers" and "red peppers" with a synonym of "peppers".  If someone says "peppers" then you get [["green peppers", "red peppers"]] because both resolutions are possible for that entity.

**Comment by tsuwandy** [comment]
Thanks @chrimc62!  Closing.
