### ISSUE TITLE
Create Root Dispatch from multiple Dispatchers

### ISSUE THREAD

**Issue by SreekanthOAuth** [microsoft/botbuilder-tools#1265]
For the previous conversation, please refer https://github.com/microsoft/botbuilder-tools/issues/1248.

thanks for providing steps. 
We followed the same steps,
1. Created childDispatch
2. While creating rootDispatch
- dispatch init -n rootDispatch --luisAuthoringKey xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--luisAuthoringRegion westus
- dispatch add -t luis --id A1xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxB1 -n childDispatch -v Dispatch --dispatch rootDispatch.dispatch
- dispatch create --dispatch rootDispatch.dispatch

Getting below exception

Failed setting up intents to child services mapping - {
  "error": {
    "code": "BadArgument",
    "message": "Maximum number of references reached. Referenced application version A1xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxB1 already references another application"
  }
}

**Comment by axelsrz** [comment]
Hey @daveta could you drive this please?

**Comment by Zerryth** [comment]
@daveta @axelsrz 

I was actually able to repro the user's error this time around just now. Per @tsuwandy, writing email to LUIS team and including Kareem

**Comment by Zerryth** [comment]
Hi again @SreekanthOAuth! 

Alright, so spoke to an authoritative voice on the LUIS team regarding the  "'Maximum number of references reached`" error. **Turns out that right now, that is the intended behavior; by design a dispatch app cannot be the intent of another dispatch app**.

And it seems that as for now, the nested dispatch scenario is not a feature that the team will implement at this time. 

(I know changes have been deployed since I originally created the nested dispatches successfully in #1248, and as of today I cannot create a "dispatch of a dispatch" scenario without error)

Thank you for raising the issue. We'll update if plans change otherwise

**Comment by Zerryth** [comment]
@SreekanthOAuth, there's an offline discussion about whether or not we should expand to more than 2-layer limit for Dispatch for our newer Adaptive Dialogs (which is currently in experimental phase).

In the discussion, the team was wondering, as a user, if the connected services portion was toggled out, ** if you minded not having the combined prediction at runtime (call resulting child LUIS app manually)**?

**Comment by Zerryth** [comment]
@SreekanthOAuth so it turns out that the error is actually non-blocking, and the 3rd layer Dispatch app actually gets created.

For example if I created something that just had 1 path like you had done in your original post:
![image](https://user-images.githubusercontent.com/35248895/63387068-5cec3380-c359-11e9-8a41-b87cde0dcd0a.png)

Commands Ran:

```
dispatch init -n MommyDisp --luisAuthoringKey "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" --luisAuthoringRegion westus
dispatch add -t luis --id aexxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx57 -n PythonBookFlight -v 0.1 -k xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
dispatch create --dispatch MommyDisp.dispatch

dispatch init -n GrandfatherDisp --luisAuthoringKey "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" --luisAuthoringRegion westus
dispatch add -t luis --id 1axxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx31 -n MommyDisp -v Dispatch -k xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
dispatch create --dispatch GrandfatherDisp.dispatch
```

1. `MommyDisp` is successfully created with a `serviceConnection` to child `PythonBookFlight`
  * "`intents`" of `MommyDisp`
 ```
"intents": [
    {
      "name": "l_PythonBookFlight",
      "serviceConnections": {
        "type": "LUIS",
        "appName": "PythonBookFlight",
        "appId": "aexxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx7",
        "appVersion": "0.1",
        "region": "westus",
        "luisIncludedIntentNames": []
      }
    },
    {
      "name": "None"
    }
  ]
```

2. `GrandfatherDisp`
**Console Output with Non-Blocking Error**

* The error means Dispatch CLI could not establish a `serviceConnection` string due to the LUIS limit of 2-layer hierarchical Dispatch

![image](https://user-images.githubusercontent.com/35248895/63387315-f582b380-c359-11e9-8791-cdb55fada4f3.png)

In LUIS portal (for me it's luis.ai), despite warning, `GrandfatherDisp` was actually created
![image](https://user-images.githubusercontent.com/35248895/63387437-38448b80-c35a-11e9-910f-303c78691fca.png)

And it properly sets `MommyDisp` as an intent
![image](https://user-images.githubusercontent.com/35248895/63387485-5c07d180-c35a-11e9-9e7e-f640b8027b0f.png)

```
  "intents": [
    {
      "name": "l_MommyDisp"
    },
    {
      "name": "None"
    }
  ],
```


Since the dispatch model is successfully created in LUIS, now in your bot logic, being aware of the intent names in both apps, you can call LUIS accordingly to traverse down your multi-Dispatch hierarchy.

___

So currently if you want a multi-layered Dispatch model, then you must traverse down the multiple layers, calling the children manually. We may change this in the future work with integrating our CLI tools with our new plans with dialogs.

**Comment by SreekanthOAuth** [comment]
Hi Zerryth, Thanks for the detail explanation. But I have a query here, i.e., if the LUIS model of type dispatch then we are observing **BadArgument: Analytics are not supported for Dispatch applications**.

If you take my example, for **childDispatch** we can see the   **BadArgument: Analytics is not supported for Dispatch applications**. But whereas in **rootDispatch** we will not see the same error/info. 

Would this cause any impact?

**Comment by tsuwandy** [comment]
@SreekanthOAuth, the error on LUIS portal is benign, I have notified LUIS team a while back about this and I’ll ping them again.  For now, just ignore the error on the portal.  Thanks!

**Comment by SreekanthOAuth** [comment]
Thanks for the confirmation tsuwandy.
