### ISSUE TITLE
Unable to create a dispatch model from Staging version of Luis App's

### ISSUE THREAD

**Issue by singzzz** [microsoft/botbuilder-tools#1413]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: 
OS: Mojave

## Describe the bug
I am unable to re-train a Dispatch model using Staging versions of Luis Apps. Given that the underlying production models have changed, I want to be able to test them and the resulting dispatch model prior to publishing them live. 

## To Reproduce
Steps to reproduce:
1. Create a set of LUIS Apps
2. Build a dispatcher using them
3. Make a change to a Luis App and publish to Staging

## Expected behaviour
I can build a Staging version of the dispatcher based on the Staging version of the Luis apps

[bug]

**Comment by anusharavindrar** [comment]
@singzzz just to clarify that you are having issues to re-train your app or publish your app? You are testing this on which browser? Do you get any error on the portal or in the Debug Console?

**Comment by singzzz** [comment]
I am retraining the dispatch after making changes to the underpinning Luis **Staging** models. 

This works fine if I publish the reference models and retrain the dispatch on production, but I want to test my changes in staging first. I can't find any documentation on this, so maybe this is a feature gap with the dispatch tool?

The issue is with the Dispatch command line tool, so not running in a browser..

**Comment by anusharavindrar** [comment]
@singzzz just to make sure I am following what you have reproduced till now:

- Created your dispatch model.
![image](https://user-images.githubusercontent.com/48731427/75294453-52659780-57dd-11ea-854d-482d35256ec5.png)
 where 
--publishToStaging | (optional) Default to false. Publish to LUIS staging instead of production platform

- Made changes to your model and now want to train and publish the existing model.
![image](https://user-images.githubusercontent.com/48731427/75294905-66f65f80-57de-11ea-8e0f-b978231536af.png)
where 
--publishToStaging | (optional) Default to false. Publish to LUIS staging instead of production platform

Please feel free to correct or add the steps you have followed and a screenshot of what error you are getting on the CLI when you try to retrain your staging model.

**Comment by singzzz** [comment]
Hi @anusharavindrar, thanks for your reply.

Steps to recreate are as you describe, with a slight clarification (point 3):

1. Create LUIS App's
2. Create Dispatch model from App's
3. Make changes to source App's and publish changes to **Staging** slot
4. Refresh dispatch model to Staging, **but using the source app staging slot, not production**

Does that clarify my problem? Is there any way to achieve this?

best
singzzz

**Comment by anusharavindrar** [comment]
@singzzz based on a similar issue in #1387 ,

**Dispatch is not supported for staging slot.** In order to test the behavior of the dispatch without having to publish on the production slot, there is actually an alternative way using the direct version publishing functionality.

Direct version publishing is a feature that enables publishing the application with the identifier not as the slot (PRODUCTION/STAGING), but rather as the version Id.

So to achieve your scenario, you can do the following:

1. Publish the updated child model using direct version publishing. This can be done only via calling REST API for now (not yet available in the LUIS UI) by setting the "directVersionPublish"flag in publish request body to true. API reference here.
2. Make sure that the dispatch parent is linked to the same versionId as the one used in direct version publishing.
3. After republishing the dispatch parent, you are expected to see the results of the child application version that was published with direct version publishing. An important note is that this will change all the published slots of the dispatch parent to point to the directly published version of the child.
4. **Optionally, if you want to test changes in the dispatch parent model itself without publishing it to the PRODUCTION slot, you can actually use direct version publish the dispatch parent, and query it with the [endpoint V3 APIs](https://westcentralus.dev.cognitive.microsoft.com/docs/services/luis-endpoint-api-v3-0-preview/operations/5cb0a9459a1fe8fa44c28dd8)**.

Hope this helps.

**Comment by anusharavindrar** [comment]
@singzzz does this answer your query?

**Comment by anusharavindrar** [comment]
Closing the issue as resolved.

**Comment by singzzz** [comment]
> @singzzz does this answer your query?

@anusharavindrar thanks, I'm not familiar with the directVersionPublish flag or how it works, so not sure if this does fix my problem, but your response did help. The steps we to achieve a staging dispatch are as follows:

1. Add new intent to Luis app and publish to Staging and unit test
2. Clone app as 'temp' then update reference to temp in the dispatch CLI
3. Publish dispatch to Staging and Test
4. Publish all apps and dispatch model to production

Do you see a problem with this approach?

singzzz
