### ISSUE TITLE
How to update existing dispatch file ?

### ISSUE THREAD

**Issue by rajeeshmenoth** [microsoft/botbuilder-tools#1429]
## Tool
Name: LUIS Dispatch
Version: 1.6.6
OS: Windows 10 Enterprise

## Describe the bug
I want to update new qna information into already created dispatch file.

## To Reproduce
1. Created dispatch file using the help of [microsoft docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs#create-the-dispatch-model)
2. Dispatch file is created after running "dispatch create" command
3. Trying to update dispatch file with new qna information
4. Not able to find any command for existing dispatch file update

## Expected behavior
Want to update existing dispatch file with new intent information ( qna or luis ).

[bug]

**Comment by Zerryth** [comment]
@rajeeshmenoth the command is `dispatch add [options]`
You can find a whole list of the dispatch commands in the botbuilder-tools repo [here](https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch#adding-source-to-dispatch).

I will make note to the docs team regarding the documentation you linked--specifically how it doesn't make mention of the list of dispatch commands available in one consolidated README, and I could see how you were left to believe that there was no such command to update an existing dispatch file.
___
One last note, as a reminder, the Bot Framework repos are for reporting bugs and requesting feature requests. If in the future you have a how-to question regarding the framework, please elicit the help of the community at large on [Stack Overflow](https://stackoverflow.com/search?q=%23botframework)

**Comment by rajeeshmenoth** [comment]
@Zerryth as of now this command `dispatch add [options]` is only support for initial adding of LUIS intent and Qna maker kb integration. Once I run this command `dispatch create` then you can't able to add newly created LUIS intent and Qna maker kbs integration into the existing dispatch file. I saw one update command in the document but that is going to update the main LUIS secret key. 

Eg. In future new KB added in Qna maker and those kb i want to update in existing dispatch file ( q_sampleKb-qna )

**Comment by Zerryth** [comment]
I see. 

Use`dispatch add` and `dispatch refresh` commands depending on what you're trying to do.

* `dispatch add` if you "In the future add a new KB", since it's not a part of the dispatch model yet
*`dispatch refresh` ([ms docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs#to-update-or-create-a-new-luis-model), [bb-tools](https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch#refreshing-your-dispatch-model)) if you've updated the underlying QnA/LUIS models that are already in dispatch - this will update the LUIS dispatch app

Are you having trouble with

**Comment by rajeeshmenoth** [comment]
@Zerryth, Thanks it's working and please update in the document as well.
