### ISSUE TITLE
Refresh dispatch model without losing entity mapping

### ISSUE THREAD

**Issue by narulasrinivas** [microsoft/botbuilder-tools#1432]
#### What project is affected?
Dispatch model refresh losing all the changes to `Intents ` and `Entities`.

#### What language is this in?
C#

#### What happens?
I'm understanding the concepts of BOT Framework by following [documentation](https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/customize-assistant/csharp/4-edit-your-cognitive-models/).

Entities and Intents are wiped off when dispatch model is refreshed.

#### What are the steps to reproduce this issue?
Step 1: Followed steps to create new KB and then `cognitiveModels.json` is updated with new values and `.\Deployment\Scripts\update_cognitive_models.ps1 -RemoteToLocal` command need to be executed which will update Dispatch model.

Step 2: For make BOT more user friendly, added few `entities `and mapped to `Intents`. Till here everything works fine.

Step 3: Repeated step 1 then `entities `which were mapped earlier are wiped off.

#### What were you expecting to happen?
When I add,update,modify QnA KB, entities which already created should stay in.

Please let me know what I'm missing in achieving it.

**Comment by narulasrinivas** [comment]
Thanks @lauren-mills.  @sidmore - Can you throw some light on how to manage `Intents` and `Entities`  when deployed via CLI?

**Comment by narulasrinivas** [comment]
@tsuwandy - Please help me with this.

**Comment by tsuwandy** [comment]
@narulasrinivas, where did you add the intents/entities?  To the dispatch LUIS app via LUIS portal?  Any changes done to the dispatch app on portal won’t be persisted next time dispatch app is refreshed from cli.  Could you clarify your scenarios?  Why do you need to add intents to the dispatch app directly?  Can the intent be added to the sub LUIS app instead?  Also entities in sub LUIS app are not transferred directly to dispatch app, except for this used in patterns.

**Comment by hcyang** [comment]
hi @narulasrinivas, below are some common Dispatch use-cases:

1) A user already has one or more LUIS, QnA Maker apps/models, or even some flat files of intent-utterances and the user would like to create a meta-app to dispatch bot traffics to those child apps. In this scenario, entities should be (manually) added to the child LUIS apps instead of to the Dispatch parent app, so that the entity definitions won't get wiped out after the Dispatch app/model is refreshed as @lauren-mills and @tsuwandy had indicated.
2) A user has a LUIS app and he/she can use Dispatch to evaluate the app's intent prediction performance in a 5-fold cross validation process.

As you can see from the scenarios, Dispatch focuses on intent prediction/dispatching and evaluation, so that entity definitions are not persisted. Please maintain your entities in the child apps, not at the Dispatch level.

I am going to close this issue for now. If you have more questions, please feel free to reopen it.
