### ISSUE TITLE
[Dispatch] Dispatch refresh fails using ErrorActionPreference set as Stop

### ISSUE THREAD

**Issue by FedericoBernal** [microsoft/botbuilder-tools#1474]
## Tool
Name: [botdispatch](https://www.npmjs.com/package/botdispatch)
Version: [1.7.1](https://www.npmjs.com/package/botdispatch/v/1.7.1)
OS: Windows

## Describe the bug
Dispatch refresh fails using $ErrorActionPreference set as Stop executed in PowerShell.

## To Reproduce
1. Have a deployed dispatch
1. Open a new instance of PowerShell
1. Configure $ErrorActionPreference as Stop
`$ErrorActionPreference = 'Stop'`
1. Execute the dispatch refresh with hardcoded values
`dispatch refresh --version Dispatch --dispatch "<PATH_TO_DISPATCH_FILE>" --dataFolder "<PATH_TO_DISPATCH_FOLDER>" 2>> "<PATH_TO_LOG_FILE>" | Out-Null`
1. See that the dispatch refresh is stopped and the log file doesn't contain any output

![](https://southworks.slite.com/api/files/s3QViToiQ5/image.png)

 
## Expected behavior
All the errors should be appended on the log file and the execution should be working successfully.

## Additional context
See microsoft/botframework-solutions#3662

Changing the $ErrorActionPreference to Continue, the execution works.

![](https://southworks.slite.com/api/files/I1yp7orfzR/image.png)

[bug]

**Comment by tsuwandy** [comment]
@FedericoBernal, when running in PowerShell or remotely from ci/cd pipeline, use "--remote true" for dispatch create/refresh command.   This is because dispatch allows std in (piped in output of another the old msbot cli to dispatch cli) -- this behavior is not compatible in powershell.   You might still need $ErrorActionPreference to Continue if running from PowerShell.

I'll close this issue and let me know if you are still having issues with Dispatch with the workarounds.  Thanks!

**Comment by FedericoBernal** [comment]
Thanks @tsuwandy for your quick reply. As you mentioned, we still need `$ErrorActionPreference` to `Continue` as it's executed from PowerShell after adding the `--remote true` for the dispatch refresh command.

This issue is solved changing the ErrorActionPreference to Continue :blush:.
