### ISSUE TITLE
Error: The limit of 20000 has been exceeded.

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/botbuilder-tools#285]
**Describe the bug**
Based on the limit mentioned here [https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-boundaries#model-boundaries](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-boundaries#model-boundaries)
luis list entity can have upto 20K sublists in it. 

Not sure if I am running into existing bug ?

I am using luis cli tool to load sublists to my list entity. After 6K to so items I am seeing following error on cmd 
```
Error: The limit of 20000 has been exceeded.
```

technically I should not get this error as limit is 20K. But if I use luis UI to add more to list entity it accepting it. 

**To Reproduce**
1. Go to luis app and create list entity 
2. Add items to list entity by valid json format
3. After loading 6k items or so cmd line shows error
4. goto luis ui > app > list entity > add data manually. 

**Expected behavior**
I should be able to use luis cli tool to load items upto 20k as per limit. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32375467/43374037-3cc6a44e-9373-11e8-9894-ee7d4066a565.png)

ui show I havnt reached the limit 20k yet. There 666 pages /page so total 6660 sublists.

![image](https://user-images.githubusercontent.com/32375467/43374055-5827cce0-9373-11e8-8a39-7b68e78fa73e.png)

**Comment by rjgmail88** [comment]
Any update on this please ?

**Comment by cleemullins** [comment]
@rjgmail88 I've sent this to the LUIS Support team. You should hear shortly.

**Comment by rjgmail88** [comment]
@cleemullins , thank you.

**Comment by rjgmail88** [comment]
Sometimes I'm getting this error 

```
List entity "letme" cannot exceed the phrases limit 20000.
```

**Comment by Zerryth** [comment]
@rjgmail88 Looking into the matter now. And actually, could you please share the JSON you're using to create the list entity with?

**Comment by rjgmail88** [comment]
I am waiting on approval to share json with you. However, issue could be reproduced with any large dumpy json that you might have.
Also, I have few questions on the luis concepts when it comes to lists which will clarify this issue. 

Firstly,  ListEntity limitation mentioned [here](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-boundaries#model-boundaries) says limit on Parent: 50, child: 20,000 items
**what is parent list and child list ?**
example json while creating LIST entity looks for following json format 

```
[
    {
        "canonicalForm": "Egypt",
        "list": [
            "Cairo",
            "Alexandria"
        ]
    },
    {
        "canonicalForm": "USA",
        "list": [
            "California",
            "Texas"
        ]
    }
]                   
```

can we call each list for canonicalForm as child ?

Secondly, API [doc](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c14)
talks about same kind of limitation 'The total item count across all sublists is 20,000.' 
but it's while creating closed list entity.

**Is closed list same as example list ?**

Thirdly, CLI [tools doc](https://github.com/Microsoft/botbuilder-tools/blob/master/LUIS/readme.md) mentions about ClosedList. and one of the cmd looks like 'luis update closedlist......' which says it can Add a batch of sublists to an existing closed list.

So I want to make sure whatever I am doing is correct. If closed list is same as List entity.

**Comment by rjgmail88** [comment]
@Zerryth, I did sent you an email with json attached.  Please let me know if you need anything else.

**Comment by rjgmail88** [comment]
@Zerryth ,any update on this ?

**Comment by Zerryth** [comment]
@rjgmail88 I did get your email and a Skype message from Andrea Martini who was assisting you earlier as well. 

# Part I

## Summary
Thank you for sending over your JSON model. Given the file, it appears the **root cause of the issue is ultimately the formatting of your schema here**. (I suspected as much yesterday, however wanted to confirm with seeing the model directly). 

> using luis cli tool...technically I should not get this error as limit is 20K. But if I use luis UI to add more to list entity it accepting it.

I also asked Andrea Martini, who was in communication with you, to clarify, _how_ exactly you were putting in the list entities when using the UI, because yes, if you had tried entering just Normalized Values and Synonyms to a List Entity one by one through the UI, you would not get an error (which is the result you described yesterday)--however with the JSON model you had given me there were two errors that actually **do** raise when you're using the **Import values** option to create the list entity via UI (invalid syntax, and over 20,000 items)

Let's go through your questions step by step, getting the easy questions out of the way first, then clarifying documentation and entity concepts.

___

> ### Is closed list same as example list ?

**ClosedList is the old/original/API term for the list entity. ClosedList API and List Entity in UX are the same.**

___
Looking at your model, it seems we should clarify when exactly is a good use case for a list entity. As described in the [documentation here](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-concept-entity-types), a list entity is

>"Best used for a known set of variations on ways to represent the same concept."

The documentation's [list entity quickstart](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-quickstart-intent-and-list-entity) gives a good example of a list entity called Employee. Each employee can be referred to in many ways, but represent one concept. For example, I can be 

- Employee-ABC (normalized value) and synonyms to refer to me can include ashley@microsoftemployee.com, 206-555-5555, etc.
- And you could be Employee-DFG with synonyms including rjgmail88@yourcompanyname.com, 555-123-4567, etc. 

Regarding your question, 

> ### what is parent list and child list ?

This is best answered with an example.

**The parent is the Employee list entity. Two child lists of the Employee entity would be the list of synonyms of each employee.** (In the example above, Employee-ABC and Employee-DFG would be children of Employee list entity)

___

### Now, going into your JSON model that you had given me that you were trying to use to create your list entity

**Syntax**
Using the GUI at luis.ai, I uploaded your JSON that you had provided to try to create a list entity, resulting in an error right off the bat: 
![invalidsyntax](https://user-images.githubusercontent.com/35248895/43487523-c3b146cc-94cb-11e8-86ab-a4ecc55e5828.PNG)
"Invalid sublists syntax in JSON file" error occurs.

Investigating your JSON file, I found that its skeleton followed this format:
```
{
    "subLists": [
        "canonicalForm": "...",
        "list": [ "...", "..." ]
    ]
}
```

Instead LUIS is looking for a JSON with this format (an array of objects with properties "canonicalForm" & "list"):
```
[
    {
        "canonicalForm": "Obi-Wan Kenobi",
        "list": [
            "Ben Kenobi", "Rako Hardeen", "Obi"
        ]
    },
    {
        "canonicalForm": "Anakin Skywalker",
        "list": [
            "Darth Vader", "Annie"
        ]
    }
]
```

**Limits**
Getting clarification from the LUIS docs team:
- A single list entity can contain up to 20,000 items max
- The 20,000 items can be a combination of canonical names and synonyms. 
- For example you can have 10,000 canonical names and each have 2 synonyms

Just by quickly Ctrl + F to search for "canonicalForm" in your JSON, you already had "17,475", plus they each had at least 1 synonym listed, meaning you had at least 34,950 items in your list entity, which is greater than the 20,000 item limit (thereby triggering the error you've been seeing).

**Comment by Zerryth** [comment]
# Part II
With that being said above, if you 

1. Fixed the syntax of the JSON you're trying to import the values from and
2. Ensured that the number of items within your List Entity is within 20,000

You should be able to create list entities in both command like and GUI.

____

However I did want to bring up one thing. Not seeing your entire language model, I don't fully understand what it is that you are trying to do with your list entities. But from the JSON you have provided me, it looks like for the most part you had made a name a canonicalForm that included capitalization and the synonym the exact same thing as the canonicalForm, but with all lowercase.

Wanted to chime in that LUIS **will automatically ToLowerCase** all of the tokens in its algorithm. 
So ultimately distinguishing between, for example, between "Schiau" and "schiau" (found in your JSON file), is not necessary.

**Comment by rjgmail88** [comment]
@Zerryth , the reason you have an error after uploading json I gave is that you used UI. I mentioned in my original post is I'm using cli tool and thats when i was getting 20K limit error.

cli tool form 

```
{
    "subLists": [
        "canonicalForm": "...",
        "list": [ "...", "..." ]
    ]
}
```

UI form 

```
[
    {
        "canonicalForm": "Obi-Wan Kenobi",
        "list": [
            "Ben Kenobi", "Rako Hardeen", "Obi"
        ]
    },
    {
        "canonicalForm": "Anakin Skywalker",
        "list": [
            "Darth Vader", "Annie"
        ]
    }
]
```

**Comment by rjgmail88** [comment]
@Zerryth ,

Firstly, thank you for your detailed response on this and we really appreciate your help. I have few followup questions and need your advice on somethings before we close this ticket.  

> Not seeing your entire language model, I don't fully understand what it is that you are trying to do with your list entities.

I am creating 2 List entities, FirstNames and LastNames which will be used in Composite entity called FullName. We have a Cortana skill which needs to understand full name from utterance ex:- 'What is the location of Rohit Jadhav' where Rohit is part of FirstNames entity and Jadhav from LastNames so FullName becomes Rohit Jadhav.
Now our corporation have almost 20K associates but by removing duplicates names I got json model for first names to 8k, and last names closed to 17k. (the one I shared with you.)

**Advice:**
I was able to load FirstNames model easily because it has 8k  canonical names/objects. How do I fix last names jason which has unique 17K  canonical names ?

1. Can I remove list that comes with each canonicalForm ? or I need to keep it at least 1 value for Synonyms population?
2. You mentioned 20,000 items can be a combination of canonical names and synonyms. The only reason I'm keeping list with each canonicalForm so that if someone types 'rohit' instead 'Rohit' it should get recognized by luis entuty value 'Rohit'. 

```
[
    {
        "canonicalForm": Rohit",
        "list": [
            "rohit"
        ]
    }
]
```

3. If list isn't necessary to maintain then I guess I can load Lastnames file (the one I gave you) in single list entity. Provide all the forms of names will be recognized. ex: rohit, rohiT, roHit etc.

**Comment by Zerryth** [comment]
@rjgmail88 

You can absolutely create list entities without values in "list" properties like so:

```
[
    {
        "canonicalForm": "Ashley",
        "list": []
    },
    {
        "canonicalForm": "Jason",
        "list": []
    }
]
```

The above would import "Ashley" and "Jason" into my list entity as normalized values, without any synonyms. 


And correct, rohit, rohiT, roHit, etc. would all be detected if you have just the normalized value of "Rohit" entered in your list entity.

**Comment by rjgmail88** [comment]
@Zerryth, thank you.
