### ISSUE TITLE
dispatch-cli create command throws error on path parameter

### ISSUE THREAD

**Issue by robkostermans** [Microsoft/botbuilder-tools#323]
After running de dispatch create command I get the following error...
running command> dispatch create --bot wbs.bot --luisAuthoringRegion westeurope

Exporting services for dispatch...
Exporting qnaname QnA kb...
Exporting luisname LUIS application...
Creating dispatch LUIS model json...
Creating training data...

Value cannot be null.
Parameter name: path

what am I missing... which "path" parameter are we talking about and where should it be set?

**Comment by Zerryth** [comment]
@robkostermans 

1. how did you run the command `dispatch init [options]` first, before trying the `dispatch create` command? More specifically, what options did you include?

I ask, because you seem to be using optional `--luisAuthoringRegion` in your **`create`** command, when looking at the botbuilder-tools dispatch repo it looks like `--luisAuthoringRegion` should be used with **`init`** command

Note in [Dispatch repo](https://github.com/Microsoft/botbuilder-tools/tree/master/Dispatch#creating-your-dispatch-model) it does not show `--luisAuthoringRegion` as an option for `create`

For example 
`dispatch init -n TestDispatch --luisAuthoringKey F57AEEEBE67349C282E1DC51F6BA66D9 --luisAuthoringRegion westus `

2. Additionally, trying to repro what you've done, how did you create your .bot file?
I get a different error when I attempt your command, so seeing the exact commands you input would be helpful

**Comment by tsuwandy** [comment]
@robkostermans, could you share your bot file with @zerryth and see if she could repro?  Make sure not to copy and paste here since it contains keys..  Btw, any reason why you specify luisAuthoringRegion for create?

**Comment by Zerryth** [comment]
@robkostermans 
Update:
Successfully created dispatch model doing the following steps:

`npm install -g botdispatch`

`dispatch init -name YourDispatchAppName -luisAuthoringKey "YOUR-LUIS-AUTHORING-KEY" -luisAuthoringRegion westus`

`dispatch add -type luis -id "YOUR-SubLuisApp-ID" -n homeautomation -v 0.1 -k "YOUR_LuisSubscriptionKey"`

`dispatch create --bot 57942.bot --luisAuthoringRegion westus`

**Comment by Zerryth** [comment]
Success! Glad it worked out in the end :)

Also thanks for the clarification and feedback on where the confusion came from.
