### ISSUE TITLE
Unable to use the command line luis list querylogs

### ISSUE THREAD

**Issue by yanick1** [Microsoft/botbuilder-tools#627]
## Tool
Name: LUIS
Version: 2.0.13
OS: Windows 10

## Describe the bug
When using the command line "luis list querylogs" I have the following error:
```
Unknown resource: querylogs

LUIS Command Line Interface - © 2018 Microsoft Corporation

Gets the query logs of the past month for the application.

Usage:
luis list querylogs --appId <string>

Command arguments are:
 --appId <string>          The application ID.
 (required)
```

## To Reproduce
1. Have a completed .luisrc file with your app infos
2. run the command `luis list querylogs`

## Expected behavior
A list of the query logs of the past month

## Additional context
I used Postman to test if I could fetch the logs with a simple Get and I was able to do it using my appId and subscription key. I also tried to add the appId to the command line and still no luck. I can use `luis list versions` ou `luis get settings` without any issue.

[bug]

**Comment by Zerryth** [comment]
Update: repo'd the issue, and hunted down the bug. Working on a fix

**Comment by Zerryth** [comment]
Update 2: 

### Part I

**Short version: Looks like we need to find the right method from _ms-rest-js_ module to call when handling response type "`stream`" in the LUIS CLI source code**

As per Chris, I will connect with southworks team and see if they have any guidance

**Comment by Zerryth** [comment]
### Part II

Detailing investigation here to update BF team and also not repeat myself when connecting with southworks via email to discuss further:

Cloning the LUIS CLI repo, then looking at the `luis.js` file, you can find the switch case where it handles the various "`luis list`" commands (e.g. `luis list entities`, `luis list intents`, etc.). There I think 17 or so `luis list` commands total.

### **Issue 1** 
There's no case for "`querylogs`", therefore triggering the familiar `Unknown resource: querylogs` error that @yanick1 reported

_`luis.js`_
![image](https://user-images.githubusercontent.com/35248895/47401839-b9f66900-d6f7-11e8-93cb-6ea8ba2eabe7.png)

___
Following all the other `luis list` commands cases, you can see that they call a `list<CommandName>()` method off the `client` (e.g. `result = await client.model.listEntities(args.region, args.appId, args.versionId, args);`

**You can see when drilling down into the `list<CommandName>()` that everything the pattern of have 3 parts below:**

`list<Resource>()`, `HttpOperationResponse()`, and `OperationSpec`

**`list<Resource>()` method**
```typescript
  listEntities(azureRegion: Models.AzureRegions, appId: string, versionId: string): Promise<Models.EntityExtractor[]>;
  listEntities(azureRegion: Models.AzureRegions, appId: string, versionId: string, options: Models.ModelListEntitiesOptionalParams): Promise<Models.EntityExtractor[]>;
  listEntities(azureRegion: Models.AzureRegions, appId: string, versionId: string, callback: msRest.ServiceCallback<Models.EntityExtractor[]>): void;
  listEntities(azureRegion: Models.AzureRegions, appId: string, versionId: string, options: Models.ModelListEntitiesOptionalParams, callback: msRest.ServiceCallback<Models.EntityExtractor[]>): void;
  listEntities(azureRegion: Models.AzureRegions, appId: string, versionId: string, options?: Models.ModelListEntitiesOptionalParams, callback?: msRest.ServiceCallback<Models.EntityExtractor[]>): any {
    return msRest.responseToBody(this.listEntitiesWithHttpOperationResponse.bind(this), azureRegion, appId, versionId, options, callback);
  }
```

**`HttpOperationResponse` method**
```typescript
  listEntitiesWithHttpOperationResponse(azureRegion: Models.AzureRegions, appId: string, versionId: string, options?: Models.ModelListEntitiesOptionalParams): Promise<msRest.HttpOperationResponse<Models.EntityExtractor[]>> {
    return this.client.sendOperationRequest(
      {
        azureRegion,
        appId,
        versionId,
        options
      },
      listEntitiesOperationSpec);
  }
```

**`OperationSpec`**
```typescript
const listEntitiesOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "luis/api/v2.0/apps/{appId}/versions/{versionId}/entities",
  urlParameters: [
    Parameters.azureRegion,
    Parameters.appId,
    Parameters.versionId0
  ],
  queryParameters: [
    Parameters.skip,
    Parameters.take
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "EntityExtractor"
            }
          }
        }
      }
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};
```
___

### Issue 2
**There is no `list<Resource>()` (i.e. `listQueryLogs`) method in `apps.ts`.** Only `HttpOperationResponse` and `OperationSpec` were built for `querylogs` in `apps.ts`

_**apps.ts**_

``` typescript
  downloadQueryLogsWithHttpOperationResponse(azureRegion: Models.AzureRegions, appId: string, options?: msRest.RequestOptionsBase): Promise<msRest.HttpOperationResponse<void>> {
    return this.client.sendOperationRequest(
      { 
        azureRegion,
        appId,
        options
      },
      downloadQueryLogsOperationSpec);
  }
```


```typescript
const downloadQueryLogsOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "luis/api/v2.0/apps/{appId}/querylogs",
  urlParameters: [
    Parameters.azureRegion,
    Parameters.appId
  ],
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Stream"
        }
      }
    },
    default: {}
  },
  serializer
};
```
____
### Issue 3
You cannot use `msRest.responseToBody()` method in making request to list query logs, because it is a "`Stream`" type. 
It actually appears to the ONLY stream type in the LUIS CLI, as far as I could find looking through all the `OperationSpecs`, probably because it's trying to download the history of all the endpoint hits to an app for the past 30 days.
 
In trying to mimic the requests made for all the other `luis list <resource>` commands, I did try implementing a case for "`querylogs`" and creating a method off the client for `listQueryLogs()` doing the following

_`luis.js`_
``` typescript
                case "querylogs":
                    result = await client.apps.listQueryLogs(args.region, args.appId, args);
                    break;
```
_`apps.ts`_
``` typescript
    listQueryLogs(azureRegion: Models.AzureRegions, appId: string,options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<void>): any {
      return msRest.responseToBody(this.downloadQueryLogsWithHttpOperationResponse.bind(this), azureRegion, appId, options, callback);
    }
```

But this merely returns "`OK`" in the console, not a list of the query logs.

**this is because `downloadQueryLogsWithHttpOperationResponse()`  results have undefined `asBodyText` and `parsedBody` properties**

Looking in the MS Rest module `utils` file, you can see that `responseToBody()` is not the right method to handle `Stream` type then due to lack of `parsedBody`
![image](https://user-images.githubusercontent.com/35248895/47404050-adc2d980-d700-11e8-9a03-634b21ab2e27.png)

Instead of `asBodyText` and `parsedBody` being defined, downloadQueryLogsWithHttpOperationResponse has results that define `readableStreamBody` property that has lots of detail in object value
![image](https://user-images.githubusercontent.com/35248895/47404219-53764880-d701-11e8-9172-6e7e8757b256.png)
___
Having never worked with `ms-rest-js`, I'm unfamiliar with what method would be the right to use in place of `responseToBody` to send the operation request (sendOperationRequest). This is what I'm currently investigating.

**Comment by Zerryth** [comment]
### Part III
Reconfirming what @yanick1 had mentioned earlier, the LUIS Programmatic API portion works just fine

Tested via Postman, browser, and using creating a small node project to make a call directly to LUIS API without MS Rest. CSV downloaded successfully

Issue is definitely in the LUIS CLI, specifically with using ms rest properly
