### ISSUE TITLE
Luis replace version support 

### ISSUE THREAD

**Issue by ikivanc** [Microsoft/botbuilder-tools#633]
## Tool
Name: [Ludown, luis]
Version: 1.0.35-45 , 2.0.13

I'm trying to manage my existing LUIS application via bot builder tools. I followed below steps to update my existing LUIS app then modify & publish it to my existing application.
[https://github.com/ikivanc/LUIS-Application-and-Bot-Builder-tools ](https://github.com/ikivanc/LUIS-Application-and-Bot-Builder-tools )

For updating my existing application I don't want to create a new LUIS application, using  `LUIS import application` command.

Below command only updates the name or description of the application version. 

`luis update application --in applicationUpdateObject.json --appId <string>`

Is there any way to update my existing model with modified json? If not this will be a needed feature to update existing applications to keep the same app credentials.

**Comment by garypretty** [comment]
I believe that 'luis update application' is only for updating the name / description.  To update your models intents, entities etc, you can use 'luis update version' and specify a version number using --versionId.

**Comment by vishwacsena** [comment]
@ikivanc - you can try the following - 
To import a new application version - 
```bash
> luis import version 
```
To rename application version - 
```bash
> luis rename version 
```
To delete an existing application version - 
```bash
> luis delete version
```

There isn't a LUIS replace version API. You can import a new version or use rename + import + delete old version.

**Comment by dkisselev** [comment]
For anyone that lands here with a similar scenario, here's the complete chain of commands necessary to perform an "update" in one step (🚨with a big dangerous caveat 🚨):

`ludown parse toluis --in ./<yourfile>.lu && luis rename version --versionId 0.1 --newVersionId 0.1-bak && luis import version --in ./<yourfile>.json --versionId 0.1 && luis delete version  --versionId 0.1-bak --force`

The massive side-effect with this method is that since the old revision is renamed then wiped, all the ID's change (for entities, intents, etc), and training+publishing for the app gets dropped.

This works for development purposes but will be highly unreliable for production.

**Comment by brisebois** [comment]
I added a few steps to to my workflow.

I start by pulling from luis:
```
luis export version > .\DeploymentScripts\en\general.luis
ludown refresh --LUIS_File .\DeploymentScripts\en\general.luis --lu_File .\CognitiveModels\LUIS\en\general.lu
```
Then I make local changes and push back 
```
ludown parse toluis --in .\CognitiveModels\LUIS\en\general.lu -o .\DeploymentScripts\en -n general.luis 

## version bump
luis import version --in .\DeploymentScripts\en\general.luis --versionId "0.2"
luis set --versionId "0.2"

luis train version --wait
luis publish 

## Luis Gen
LUISGen .\DeploymentScripts\en\general.luis -cs General -o .\Dialogs\Shared\Resources\

## update bot file
msbot update luis --id general --version "0.2"

## Dispatch
dispatch create -b <yourfile>.bot | msbot connect dispatch --stdin
```
Publish bot, test then delete previous version
```
luis delete version --versionId "0.1"
```

**Comment by AmirGeorge** [comment]
@ikivanc as Gary mentioned, the `luis update version` command is what you are looking for.

@dkisselev deleting an application version does not delete the published app. Training is invalidated because it is wrong for the new changed app version to have the same training state as the old app version. If you are concerned about changing model IDs, you can consider doing more fine-grained operations like adding/ updating/ deleting models from an existing app version.
