### ISSUE TITLE
Dispatch model loses prediction accuracy because patterns are excluded

### ISSUE THREAD

**Issue by dividor** [Microsoft/botbuilder-tools#641]
## Tool
Name: Dispatch
Version: 1.1.2
OS: Windows 10

## Describe the bug
Love the dispatch tool!

We have started using the Pattern feature in LUIS, which has proved to be very useful. However, when combining LUIS models with dispatch, it seems the benefits of patterns are lost because there are no entities/patterns transferred to the dispatch model. This means dispatching fails for cases where we have a very high score in the original LUIS model due to a pattern.

## To Reproduce
- Create an entity 'Person' and populate with a few names ('Dave', 'Sarah', 'Jane' and 'Darth Vader'
- Create an intent 'LookupPerson'
- Add a few utterances 'Lookup dave's number', tell me 'find me the email of Darth Vader.
- Create a pattern entity {Person}
- Train and publish the model
- Test the model, entering the utterance 'Dave' should get the 'LookupPerson' intent with a very high score
- Create a second LUIS model to do something simple, eg tell the time
- Use dispatch to combine
- Test the dispatch model for utterance 'Dave'. It will not identify this as a 'LookupPerson' model intent

## Expected behavior
I would expect patterns to apply to the dispatch model

[bug]

**Comment by Zerryth** [comment]
@dividor looking into the matter!

To clarify so I could try to repro most precisely as possible, the `Person` entity that you're creating is a **simple** entity, right?

Additionally what is the **pattern** that you are using? And are you actually testing other utterances besides just a one-worded 'Dave' for example?

### It may be more helpful if you could **[share the exported JSON of your two LUIS apps](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-manage-versions#other-actions) that Dispatch calls with us**.

I will attempt to repro  your results w/o it in the meantime, however given the potential variables, it's possible that the investigation would yield different results

**Comment by Zerryth** [comment]
@dividor we will need the **JSON of your LUIS apps** if you'd like us to investigate further.

And you are correct in that the model created with **dispatch does not bring in the entities and patterns** from the LUIS models that get added to the dispatch model, and _currently this is as intended_, correct @tsuwandy?

--however, just speculating from the information given and not knowing for sure without your models, the LUIS app that you created that has the pattern probably **should be built in a different way to detect the LookupPerson intent**.

**Comment by Zerryth** [comment]
> --however, just speculating from the information given and not knowing for sure without your models, the LUIS app that you created that has the pattern probably **should be built in a different way to detect the LookupPerson intent**.

I say this because, if I am understanding you correctly, you are using only "`{Person}`" as the entire pattern itself like so:

![image](https://user-images.githubusercontent.com/35248895/46639475-1c0d7680-cb1b-11e8-9787-8dc9cf52b010.png)
which is actually not the best use of the LUIS Pattern feature, because as stated in the [LUIS best practices docs](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-concept-best-practices#do-add-phrase-lists-and-patterns-in-later-iterations), Patterns should be used to help with intent prediction accuracy by using the combination of word choice **and placement** of the words. If your pattern is actually just "`{Person}`", then there's nothing surrounding the placement of your entity to help detect where it should be placed within an utterance. 
_______________
See repro below and two tests to illustrate:
1. Created HumanResource app (can find model in article [How to add Patterns to improve prediction accuracy](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-model-intent-pattern))

2. Created `Person` entity, `LookupPerson` intent, and added your example utterances provided in your original post "`Lookup dave's number`" and  "`find me the email of Darth Vader`".
![image](https://user-images.githubusercontent.com/35248895/46640807-01d79680-cb23-11e8-86d7-1718d775f065.png)

3. Testing

### Test results **without** adding pattern `{Person}` to model
![image](https://user-images.githubusercontent.com/35248895/46640782-d18ff800-cb22-11e8-943b-b67b9ac0d546.png)

Notice how when we enter an utterance ("`dave`") that does not match any example utterances in the LookupPerson intent, LUIS does not detect the utterance to mean the LookupPerson intent in our  model.

### Test results **with** pattern `{Person}` added to model
![image](https://user-images.githubusercontent.com/35248895/46640993-f3d64580-cb23-11e8-8ef1-1e8f2932b37c.png)

Notice how only the utterance "`lookup dave's number`" is the only utterance that LUIS is more confident about after adding the pattern `{Person}` to the app, because it 
1. shows up matching an example utterance in the `LookupPerson` intent following the context of `lookup {Person}'s number` 
2. "dave" is actually labeled directly on the example utterance, so LUIS can detect that "dave" is a `{Person}` entity with the 2nd signal of the LUIS pattern 

It can't, however, detect that "`caroline`" is an entity within the pattern itself if the pattern is just `{Person}`, because there _are_ words surrounding around "caroline" in the utterance "`lookup caroline's number`", so the utterance does not get an extra signal boost from pattern added to its confidence score.

### Test results at the dispatch  model level
![image](https://user-images.githubusercontent.com/35248895/46641552-174ebf80-cb27-11e8-9b2d-e48cba9de773.png)
- Not so surprisingly, the utterance "`dave`" fails at the dispatch app level as well, just like in the previously tested sub LUIS app.
- the other two utterances ("`lookup dave's number`", "`lookup caroline's number`") are distinct enough between the two LUIS apps I added to dispatch model (HumanResource app and WeatherV4 app). Just like in our sub-LUIS app, dispatch correctly predicts that they are utterances from an intent within the I_HumanResource app, even without use of patterns in the dispatch model.

### Summary
So, you can see that although dispatch models do not import patterns or entities automatically, you can design your model 

1. design your LUIS models to accurately predict intents with good variations in your example utterances (recommended)
2. manually add entities and patterns in your dispatch model to help point it to the proper sub LUIS model

**Comment by Zerryth** [comment]
### **This issue is probably more suited for [StackOverflow](https://stackoverflow.com/search?q=%23botframework)**. 
If you have further how-to-design-your-luis-models questions, please do so there, with a "luis" tag.

Pending confirmation from dev team who works on dispatch to confirm whether or not the lack of entities and patterns in the dispatch model is:
1. a bug or is actually intended to be built this way currently (what I am not 100% sure of)
2. should be tagged as feature request or not

**Comment by dividor** [comment]
Hi Zarryth,

Thanks very much for taking the time to respond.

Actually patterns have a dramatic effect on our production models. We are using them exactly as intended, to boost an intent for looking up a person’s details. We have utterances of “lookup {person}”, but a very common use case is somebody just entering the person’s name “{Person}”.

Previously we used a custom Recognizer to intercept names (6,000 of them in the directory), but with patterns we are able to totally remove that and simply have a single “{Person}” pattern. It works really well for any of the names (and their synonyms) in the directory.

I think dispatcher is a fantastic tool and we are already using it. My point here is that there is a fairly new powerful feature (Patterns) which if excluded means the dispatcher works very different to the sub-model, and so will be incorrect. Our use case might be unusual, but *any* use of patterns will male dispatcher impossible to use.

Hope that help give more of a picture.

Thanks

**Comment by tsuwandy** [comment]
@dividor, your point is valid.  I agree if child model makes use of the pattern, then the same should be done on the Dispatch level.

**Comment by tsuwandy** [comment]
Latest Dispatch with the requested feature is published to npmjs.

**Comment by dividor** [comment]
Woah! Fantastic! Thanks.

**Comment by gnoto96** [comment]
Following up on issue

##Tool
Name: Dispatch
Version: 1.1.5
OS: Windows 10

##Describe the bug
Downloaded new version of **botdispatch** package (1.1.5) to try to incorporate patterns and entities, yet I continue to get the following error when attempting to import the dispatch model to LUIS:

ERROR: Failed importing <modelname> app

##To Reproduce
This came up both when trying to use 'dispatch **refresh** --dispatch <modelname>.dispatch' on an existing model, as well as trying to create a brand new model following the documentation steps:
dispatch init -n <modelname> ...
dispatch add (models)
dispatch create --dispatch <dispatchname>.dispatch... 

Following output appears every time before attempting to export dispatch to LUIS:
'''
Exporting services for dispatch...
Exporting <modelname> LUIS application...
Creating dispatch LUIS model json...
Creating training data...
Updating <dispatchname> model...
Importing <dispatchname> model...

ERROR
Failed importing <dispatch> app
'''
Lastly,
I deleted the botdispatch package globally with: 
npm -g uninstall botdispatch --save

And proceeded to reinstall old versions, beginning w/ our original version 1.1.2 with command:
npm install botdispatch@1.1.2

Attempted to export dispatch model to LUIS again with command
dispatch create --dispatch <modelname>.dispatch 
This worked! (No error)

I continued to upgrade my package to version 1.1.4, and no issues with exporting model to LUIS (while entities/patterns still did not make it to the dispatch from respective child models).
Lastly, tried with version 1.1.5 once again, and ERROR persisted. 

Any help regarding the error would be appreciated - Thank you!
[bug]

**Comment by gnoto96** [comment]
@tsuwandy 
Following up on issue

## Tool
Name: Dispatch
Version: 1.1.5
OS: Windows 10

## Describe the bug
Downloaded new version of **botdispatch** package (1.1.5) to try to incorporate patterns and entities, yet I continue to get the following error when attempting to import the dispatch model to LUIS:

**ERROR: Failed importing (modelname) app**

## To Reproduce
This came up both when trying to use '`dispatch refresh --dispatch (modelname).dispatch`' on an existing model, as well as trying to create a brand new model following the documentation steps:
```
dispatch init -n (modelname) ...
dispatch add (models)
dispatch create --dispatch (dispatchname).dispatch... 
```

Following output appears every time before attempting to export dispatch to LUIS:

```
Exporting services for dispatch...
Exporting (modelname) LUIS application...
Creating dispatch LUIS model json...
Creating training data...
Updating (dispatchname) model...
Importing (dispatchname) model...

ERROR
Failed importing (dispatch) app
```

Lastly,
I deleted the botdispatch package globally with: 
`npm -g uninstall botdispatch --save`

And proceeded to reinstall old versions, beginning w/ our original version 1.1.2 with command:
`npm install botdispatch@1.1.2`

Attempted to export dispatch model to LUIS again with command
`dispatch create --dispatch (modelname).dispatch` 
This worked! (No error)

I continued to upgrade my package to version 1.1.4, and no issues with exporting model to LUIS (while entities/patterns still did not make it to the dispatch from respective child models).
Lastly, tried with version 1.1.5 once again, and ERROR persisted. 

Any help regarding the error would be appreciated - Thank you!
[bug]

**Comment by tsuwandy** [comment]
@gnoto96, I'm guessing the patterns in one of the child models use ML entities? i'm working to merge the labeling at the utterance level at the moment.  If you could share your .dispatch file (email to tiens@microsoft.com) or the exported child models, I could make sure that the new fix will handle your sub models.  Thanks very much!

**Comment by gnoto96** [comment]
@tsuwandy Hello,
Any updates on this? Haven't attempted to refresh the dispatcher w/ the new package since the error. We would still very much like to import our entities and patterns from the child models as our dispatch models are not as strong without these. 
Thanks for the help!

**Comment by tsuwandy** [comment]
@gnoto96, the latest Dispatch is published to npmjs.  Please try it out and let me know if you are still seeing issues.  Thank you!

**Comment by gnoto96** [comment]
@tsuwandy 
Hey! I updated the models with the new package (1.1.8) and all the entities and patterns from the child-models transferred flawlessly! Thank you so much for the help :D

**Comment by Cocorina** [comment]
@tsuwandy 
Hello
I installed the new version of botdispatch and got this error while trying to create the LUIS json model:

> ERROR
> Invalid pattern hello [,] [.] [!] [dear] [!] [.]

Any ideas why my pattern is invalid?
Thanks :)
