### ISSUE TITLE
LUISGen Fails to Install on Mac

### ISSUE THREAD

**Issue by justinwilaby** [Microsoft/botbuilder-tools#643]
## Tool
Name: LuisGen
Version: 2.0.0
OS: Mac

## Describe the bug
`sudo  npm i -g luisgen` fails to install and results in the following error: 
![image](https://user-images.githubusercontent.com/2652885/46632376-4bae8580-caff-11e8-8289-bf8df100dddc.png)
**Note** This error still occurs after installing the dotnet sdk.

## To Reproduce
1. install the dotnet sdk from https://www.microsoft.com/net/download 
2. run `sudo npm i -g luisgen'

## Notes
I need to install a tool to install another tool?

**Comment by sgellock** [comment]
@justinwilaby what version of dotnet is installed on your machine?

**Comment by wiazur** [comment]
I'm getting a similar error on Windows 10. I have .NET 2.1.402 installed.

![luisgen error](https://user-images.githubusercontent.com/38537084/46835828-2a020800-cd64-11e8-9ec6-20c29d660748.PNG)

**Comment by sgellock** [comment]
on a clean Win 10, with .net core sdk 2.1.403 and node v8.12.0 luisgen installation runs without errors, but luisgen is not installed.

**Comment by wiazur** [comment]
I actually found a workaround, you can install the library directly from here: https://www.nuget.org/packages/LUISGen. So when I went to reinstall the other packages, they install fine. The problem is the Newtonsoft.Json link is broken, it gives a 404 (as shown in my stack trace). So not sure how to reconfigure that with the right link, but that was the problem.

**Comment by sgellock** [comment]
LUISGen has a dependency on the .NET Core runtime.  Please install the .NET Core runtime first, then install Origen
