### ISSUE TITLE
MSA provision failure in msbot clone services

### ISSUE THREAD

**Issue by muges01** [Microsoft/botbuilder-tools#663]
I have test by running the following code 

> msbot clone services --name "EnterpriseBotDemo" --luisAuthoringKey "[myLuisKey]" --folder "DeploymentScripts\msbotClone" --location "westeurope" --verbose --appId "[myAppId]" appSecret "[myAppSecret]"

on the nightly build but i'm still getting the following error 

>  az bot create -g EnterpriseBotDemo --name EnterpriseBotDemo --kind webapp --location westeurope --insights-location "West Europe"  --version v4 exit code: 1
WARNING: The behavior of this command has been altered by the following extension: botservice
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DH5S36JC9 to authenticate.
ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again.

Any help will be appreciated.

**Note**: The account that i'm using has MSA enabled. 
msbot version: 4.0.6-86

_Originally posted by @muges01 in https://github.com/Microsoft/botbuilder-tools/pull/639#issuecomment-429982585_

**Comment by muges01** [comment]
Hi any updates regarding this?

**Comment by joseques** [comment]
Please, check your command syntax, you missed `--` before the parameter `appSecret`
The correct syntax would be
`msbot clone services --name "EnterpriseBotDemo" --luisAuthoringKey "[myLuisKey]" --folder "DeploymentScripts\msbotClone" --location "westeurope" --verbose --appId "[myAppId]" --appSecret "[myAppSecret]"`

Also, if I'm not mistaken you'll need to update `msbot` with the nightly build since the fix mentioned in #639 is applied in `msbot` version: **4.0.6-87** but I'm not sure about that so feel free to correct me if I'm wrong.

**Comment by sgellock** [comment]
We believe it's fixed in the version @joseques mentions.  If you still experience the issue, please open a new issue and we'll provide additional help.
