### ISSUE TITLE
No TypeScript support for bot creation

### ISSUE THREAD

**Issue by ryanvolum** [microsoft/botbuilder-tools#725]
## Tool
Name: [AZ bot create]
Version: Az cli 2.0.46
Win10

## Describe the problem

Related to #723, but addresses a different issue. The --lang flag takes "Node", but **Node is not a language**, it's a runtime. I don't mean to be pedantic here, but Node can be either JavaScript or TypeScript, which each have different build/deployment processes. 

I've yet to successfully deploy a TypeScript bot using the tooling, but presume that this will only work for JavaScript. 

![image](https://user-images.githubusercontent.com/3891951/47754830-620cb480-dc59-11e8-8406-2e834d6a5a62.png)

**Comment by carlosscastro** [comment]
Hello @ryanvolum !

There was a lot of focus on C# and I know that some js paths were broken until this week. Great observation on the runtime vs language, agreed.

We cannot remove 'node' as it would be a breaking change, but we could deprecate it and call it js to be more accurate perhaps. Supporting typescript is a larger endeavor and I don't know how much work is involved there.

Should we fork this one into 2 parts, i.e. 1) rename parameter to javascript and 2) support typescript? We can do 1) for the next release, but 2) could be accommodated at the earliest in 4.3 I think unless you think it is a P0.

Happy to hear your thoughts on this, thanks!

**Comment by carlosscastro** [comment]
We'll rename the option to javascript. Feel free to open a new item if you feel like we should prioritize typescript.

**Comment by carlosscastro** [comment]
After talking to the CLI folks, it's not so easy to change this parameter. Supporting javascript officially and node as a deprecated type is quite complicated, so we might add this to our breaking changes queue and plan for a set of deprecations. We are starting to work with the CLI team on how to do this correctly.

**Comment by stevengum** [comment]
Adding that the samples and yeoman-generated TypeScript bots are deployable to Azure now, due to these PRs: Microsoft/BotBuilder-Samples#1071 + Microsoft/BotBuilder-Samples#1074

**Comment by stevengum** [comment]
So this issue should be split up into a couple of separate issues.

### Re: `--lang Node`
As Carlos indicated above this is a breaking change. We don't yet have a schedule for breaking changes, but there are at least a couple that we should release at one time, as opposed to folding them in as we get them. We're putting together a plan and will convey it with developers as soon as we have one.

### Re: `az bot create --lang Typescript`
We're eventually going to support _creating_ TypeScript bots (the original issue), but that's not in the cards for 4.3. Publishing TypeScript bots is where it can get a little confusing (see next point)

### Re: `az bot publish --lang Typescript`
Regarding us handling support for publishing a developer's not-yet-transpiled TypeScript bot, I don't think this should be the responsibility of `az bot`.

**Best case scenario is for developers to transpile their code before publishing it.** Otherwise developers could either use Babel or tsc to transpile their code, and us supporting that potential matrix explicitly seems excessive.

If developers do something similar to our solution for [publishing](https://github.com/Microsoft/botbuilder-tools/issues/725#issuecomment-448352389) TypeScript Yeoman templates (and our TypeScript samples), which is to use `npm postinstall` scripts and custom scripts to modify the `web.config` file, then we support that out of the box.
