### ISSUE TITLE
Dispatch Refresh on Enterprise Template renames I_General to I_Botname_General (Breaks Bot)

### ISSUE THREAD

**Issue by AzureDataGeek** [Microsoft/botbuilder-tools#760]
## Tool
Name: Dispatch
Version: 1.1.8

## Describe the bug
Dispatch renames the Intent listing from I_General to I_BotName_General.  This breaks the Enterprise Bot Template.

## To Reproduce
1. Deploy an Enterprise Bot Template
2. Test Bot and it works fine
3. Run Dispatch Refresh
4. Bot is broken

## Additional context

[bug]

**Comment by AzureDataGeek** [comment]
When running dispatch refresh on a newly deployed Enterprise Bot Template, dispatch renames the intent from I_General to I_BotName_General.  This breaks the Enterprise Bot

**Comment by tsuwandy** [comment]
I'm going to close this since Dispatch behaves as expected given entries in the bot file.  Will follow up with Darren/Lauren on enterprise bot side.

**Comment by lauren-mills** [comment]
@tsuwandy I ran into this today and have some more information about the flow:
1. Run msbot clone with a dispatch.luis file representing a prebuilt dispatch LUIS model
2. Have a .bot file with 1 LUIS, 1 QnA, and 1 Dispatch entry. (**At this point, no dispatch command has been run, and we do not have a .dispatch file)
3. Run dispatch refresh against the .bot file (dispatch refresh --bot <my file>.bot
4. This creates a dispatch.dispatch file and renames the l_General intent from the prebuilt model to l_<proj_name>_General which breaks the Enterprise Bot code.

The ideal solution here involves being able to align the dispatch service and luis services from the .bot file with the desired intent name used in the code. One idea is to support the intent name in the dispatch service definition in the .bot file like so:

    {
      "type": "dispatch",
      "serviceIds": {
        {"general", "l_General"}
        {"faq", "l_FAQ"}
      },
      "name": "MyBot_Dispatch",
      "appId": "****",
      "authoringKey": "****",
      "subscriptionKey": "****",
      "version": "Dispatch",
      "region": "westus",
      "id": "dispatch"
    }

And use these intent names in the dispatch refresh command when the .bot file is specified.

Another option is to modify the bot.recipe for dispatch entries to accept the intent names and run dispatch create during the clone process rather than a straight dpeloyment to LUIS.

**Comment by lauren-mills** [comment]
Tagging @tomlm since this could affect msbot clone as well 😊

**Comment by tsuwandy** [comment]
@lauren-mills , @tomlm, we should discuss in person?

**Comment by tsuwandy** [comment]
Dispatch deployment is ongoing.  Should be on npmjs soon.
