### ISSUE TITLE
Ludown: Automatically fix spacing issues for entities

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#773]
## Tool
Name: Ludown

## Describe the problem
When writing .lu files, sometimes the developer will not include spaces around the `{ }` for entities. This is particularly common when using non-English languages which do not rely on spaces, like Chinese. This causes issues in the resulting .json file because the entities cannot be parsed.

Ex .lu utterance:
`- controllare il mio {RelationshipName=Mamma}programma del`

Resulting .json file:
```
 {
      "text": "controllare il mio Mammaprogramma del",
      "intent": "FindCalendarEntry",
      "entities": [
        {
          "entity": "RelationshipName",
          "startPos": 19,
          "endPos": 23
        }
      ]
    }
```
Error:
`Indices 19,23 are not the start and end of a token`

## Describe the solution you'd like
I'd like the ludown parse command to automatically fix these spacing issues during parsing

## Describe alternatives you've considered
Manually fixing all spacing issues

## Additional context

[enhancement]

**Comment by omarsourour** [comment]
@lauren-mills This issue needs some thorough explanation from my part. 

Now the way that LUIS works is that when an utterance is inputted, it passes by multiple phases of pre-processing before it is actually evaluated by the model. Some of these steps are:
- Validation (character length limit, special characters, etc.)
- Normalization (trimming white spaces, dealing with casing, etc.)
- Tokenization, which is the process of breaking the utterance into separate tokens.

I will dive deeper into tokenization because this is what we're considering here.

### LUIS tokenization
LUIS breaks utterances into separate tokens. A token is a sequence of characters that LUIS thinks can be labeled as an entity. This sequence can be as short as 1 character and as long as 500 characters (the limit of an utterance length).

The process of tokenization differs between each **application culture and another**. The way LUIS tokenizes utterances in an _en-us_ application for example, differs greatly than tokenization of a _zh-cn_ application. To clarify, let's (very shallowly) compare between the two tokenizers:
- The English tokenizer splits the utterance on white space (among other things), deeming that white space is a delimiter between two separate tokens. So the utterance "I like apples" would be tokenized to: ["I", "like", "apples"].
- The Chinese tokenizer however splits the utterance on the _character_ level, so the same utterance in Chinese "我喜欢苹果" would be tokenized to ["我", "喜", "欢", "苹", "果"].

Let's take a look at how the `.lu` utterance would be for both the utterances mentioned above, and let's assume that I want to label "apples" as a fruit:
- The English utterance would be as follows:
```markdown
- I like {fruit=apples}
```
and the generated JSON file from running the `ludown` command would be:
```json
{
    "text": "I like apples",
    "intent": "FactIntent",
    "entities": [
        {
            "entity": "fruit",
            "startPos": 7,
            "endPos": 12
        }
    ]
}
```
- The Chinese utterance would be as follows:
```markdown
- 我喜欢{fruit=苹果}
```
and the generated JSON file from running the `ludown` command would be:
```json
{
    "text": "我喜欢苹果",
    "intent": "FactIntent",
    "entities": [
        {
            "entity": "fruit",
            "startPos": 3,
            "endPos": 4
        }
    ]
}
```
Note that the spacing you see in the generated JSON utterances is both the correct and expected one. The indices are also correct, as they are indexed by _character_ before any tokenization occurs. Had we altered spacing between the characters and each other by adding extra white-spaces, we would have potentially changed the meaning of the statement.

Even more, at the time of the generation of the `.lu` file, the user has no idea how LUIS tokenizes the utterances. The user can not (and should not) predict or know how LUIS breaks down text. The user should only be writing utterances in his/her language in a way that makes sense to him/her at the time, and label entities based on what is written in the text, and let LUIS do the rest.

To demonstrate that, let's see what happens when you try importing the generated JSON files from our example above. The English utterance JSON file succeeds with no issues. However, the Chinese one will fail with an error similar to the one you mentioned above.

What is going on here? The reason is that the `ludown` command generates a JSON file that corresponds to an _en-us_ application by default. That is:
- When you upload the generated Chinese utterance JSON app, LUIS will try to tokenize the utterance as if it were an English sentence. So from LUIS's _en-us_ point of view, the Chinese utterance consists of one token: ["我喜欢苹果"]. That is, LUIS recognizes one word from characters 0 to characters 4 that is allowed to be labeled as an entity.
- If I try and label the entity `fruit` from indices 3 to 4, LUIS throws an error that that is not possible.

Luckily the `ludown` command has an option to chose a culture when exporting an `.lu` file to JSON, which is `-c` or `--luis_culture` followed by one of the cultures supported. So in our case, when running the `ludown` command to process the Chinese utterance, we will run it with a `-c zh-cn` option, to ensure that the output JSON will be parsed and understood by LUIS as Chinese. When importing the new JSON app file, it succeeds and is read by LUIS correctly.

The summary is:
- Type the utterances with the spacing and punctuation you see makes sense according to the language you are writing.
- Label the utterance with entities using the `.lu` entities syntax in the docs, and with the spacing intact.
- **Generate the JSON app file using the `.ludown` command, and use the `-c` option to ensure that the generated app is compatible to one of the LUIS supported cultures**.

**Comment by omarsourour** [comment]
@gabog Does the previous comment aid you with Microsoft/AI#321?

**Comment by lauren-mills** [comment]
Thanks, Omar. I checked our scripts and we aren't using the -c option for any of our models except Dispatch so I'll add that in and followup. But it seems like we could still see issues with parsing .lu to .luis if a dev messes up when entering their utterances, so could we get an error message that tells us where the error occurs in the file, in addition to which indices are invalid?

**Comment by omarsourour** [comment]
@lauren-mills Sure, I can look into that. Do you mind opening it as a feature request? Also, I assume that we can close this issue?
