### ISSUE TITLE
msbot connect abs will lead to botfile json where abs has serviceName and name

### ISSUE THREAD

**Issue by robert4os** [Microsoft/botbuilder-tools#778]
## Tool
Name:  Msbot
Version: *4.0.7*
OS: *windows 10*

## Describe the bug

When 'msbot connect abs' also creates an endpoint it will intermix the names of abs and endpoint services.
 
Both abs and endpoint will have the same name (from the -n parameter).

## To Reproduce

msbot connect bot --serviceName NAME1 -t XXX -s XXX -a XXX -p "XXX" --secret XXX -r XXX --endpoint https://XXX.azurewebsites.net/api/messages -n NAME2 -r XXX

This will create 

{
            "type": "abs",
            "name": "NAME2",
            "serviceName": "NAME1",
        ...
    "id": "205"
        },
        {
            "type": "endpoint",
            "name": "NAME2",
          ....
  "endpoint": "https://xxx.azurewebsites.net/api/messages",
            "id": "190"
        }

Note how NAME2 ends up in both services.

Also it is unclear to me why abs has TWO attributes 'name' AND serviceName ?

Probably one could get rid of the serviceName attribute. Actually I just tried to remove serviceName for abs from botfile and it works just fine.

## Expected behavior

--serviceName parameter should probably end up in 'name' of abs. And the -n parameter in the 'name' of the endpoint. 

Service abs in the botfile should probably not end up with a 'serviceName' attribute.

[bug]

**Comment by vishwacsena** [comment]
@robert4os this is by design. See [here](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botframework-config/src/schema.ts) for the interface type definitions.

'name' is merely an identifier for the service type in the .bot file. This can be different from the actual name of the service itself. e.g. bot file can have name='luismodel1' while the service name of the luis application is 'cafe bot en-us'. 

When you connect Azure Bot Service to your .bot file, two sections are added - one that captures the endpoint information and another that captures your bot service information. The ABS section is only used by Emulator for deep linking to the service. 

Please reactivate if you need additional clarification.
