### ISSUE TITLE
Dispatch - Unable to install/use dotnet framework

### ISSUE THREAD

**Issue by moredvikas** [Microsoft/botbuilder-tools#807]
## Tool
Name: Dispatch
Version: *tool version*
OS: *Windows 10 Education*

## Describe the bug
Unable to use Dispatch. Get error:
Unable to install/use dotnet framework

## To Reproduce
1. ...
2. ...
3. ...
4. ...

## Expected behavior
Dispatch to work

## Additional context

[bug]

**Comment by tsuwandy** [comment]
Could you try installing from a command prompt started with administrator privilege?

**Comment by tsuwandy** [comment]
@Zerryth could you follow up on this?  Not sure what's going on here.  Thanks!

**Comment by CoHealer** [comment]
Targeting Thur to investigate

**Comment by Zerryth** [comment]
**Unable to repro any errors.** 

_Versions_
**Node**: v10.14.1
**npm**: 6.4.1
**Dispatch**: 1.1.10

Followed instructions provided [here](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Dispatch) in botbuilder-tools repo on dispatch.

_Commands Ran_

Install dispatch:
`npm install -g botdispatch`

Initialize dispatch (i.e. create a .dispatch file)
`dispatch init`
Followed up by providing name of app (`AshleyInstallTest`), LUIS Authoring Key (`b7xxxxxxxxxxxxxxxxxxxxxxxxxx1467`), LUIS authoring region (`westus`)

Add a service (QnA Maker for this example)
`dispatch add --type qna --id 2xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxf07 --name qna --key 28fxxxxxxxxxxxxxxxxxxxxxxxxxxx92`

Create LUIS model of dispatch
In same folder that has the newly created `.dispatch` file
`dispatch create`

@moredvikas  It's unclear what you mean by "Unable to install/use dotnet framework", so I went further than just installing Dispatch and creating the model above. 

**In order to assist you please ensure your command line tools are up-to-date (versions?) and also provide repro steps, so we can repro your issue and dig down to a solution**

**Comment by jjgriff93** [comment]
I'm getting this issue when trying to run dispatch refresh in Command Line on an Azure DevOps hosted build agent. There isn't any additional output apart from this same message. Steps to reproduce:
1. Add enterprise bot template into source control in Azure Repos
2. Create a build pipeline with two Command Line steps, using the 'Hosted' agent
3. First step, run `npm i -g botdispatch`
4. Second step run `dispatch refresh --bot "botname.bot" --secret "botsecret"

**Comment by tsuwandy** [comment]
@jjgriff93 , no output (error or update) from "dispatch refresh" command?    How about "dispatch init"? or "dispatch -v"

**Comment by tsuwandy** [comment]
Thanks James!  Seems like something we need to add to the readme.
