### ISSUE TITLE
ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again.

### ISSUE THREAD

**Issue by gabog** [Microsoft/botbuilder-tools#813]
## Tool
Name: Msbot
Version: 4.0.7
OS: Windows

## Describe the bug
I am trying to create a bot using msbot clone in a new azure subscription and I am getting "ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again.",

I'm not clear on what needs to be done to enable automatic creation of MSA on a tenant or how to specify them as parameters. 

Is this documented somewhere?

## Expected behavior
I would like to understand what permissions are missing, what do I need to configure to get this to work and how to pass MSA id as params if the automatic step continues to fail.

## Screenshots
![image](https://user-images.githubusercontent.com/12264946/49377025-5190a380-f709-11e8-9a8f-30d87a0858c9.png)

**Comment by carlosscastro** [comment]
Hello @gabog! 

I'm looking into this. 

As an alternative to auto-provisioning, `msbot clone` receives `appId` and `appSecret` arguments where you can pass your app id and password created at apps.dev.microsoft.com. 

Also as additional information for you, the current method of provisioning an app id and password is less from ideal because it requires a second log in (after `az login`). We are working towards removing this second login and reuse your az login. 

**Question 1: Can you run `az login` with your hotmail account?** I would think you cannot, unless you have an Azure free trial for this hotmail account. In general, `msbot clone` login is similar to `az login` login in behavior. 
 
**Question 2: could you please re-run msbot clone with --verbose to get a bit more info?**

If you do have Azure subscriptions on this account and `az login` works for you with hotmail, and `msbot clone` fails, that is certainly a bug. If that is the case, we can make a plan of action to swiftly solve this issue.

A final thought is that we are drastically improving az and msbot verbose logging which should make this much easier.

While I expect your answer, I'll keep investigating this.

**Comment by gabog** [comment]
Hi Carlos, this issue happened on a customer environment and I don’t think I can try what you are asking there again. We were using Azure AD accounts to run the deployments. Manually creating the AppId and password (using the same Azure AD account but login directly to http://dev.apps.microsoft.com/ directly) and passing them as parameters worked for us.

Gabo

**Comment by stevengum** [comment]
Closing via [stevengum/Azure-Cli#f9469d8287d8c4e32c11c7e8cbe9b4a5d0831b4e](https://github.com/Azure/azure-cli/commit/f9469d8287d8c4e32c11c7e8cbe9b4a5d0831b4e).

`--appId` and `-p/--password` are now required for `az bot create` and can be provisioned via Azure CLI (`az ad app create`).
