### ISSUE TITLE
Dispatch should exclude utterances from None intent of child LUIS model

### ISSUE THREAD

**Issue by tsuwandy** [Microsoft/botbuilder-tools#843]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Dispatch should not pull utterances from None intent of child LUIS model into Dispatch intent for that child model.  ie.  for child model A, with intents x, y, z, None.  When added to Dispatch model as intent l_A, all the utterances including those from None intent are added to l_A intent.  Dispatch should exclude utterances from None intent.  

Utterances from None intent from child models will be combined into Dispatch None intent after removing conflicting utterances -- final utterances in Dispatch None intent should not exist in any of the child models (exact match only to start).

## Additional context

[enhancement]

**Comment by genbod** [comment]
I am not sure this is the right solution.  Because None is not an exact match using specific None utterances from a child model can really mess up the parent None intent.  I just had an issue where None on the Dispatch model was matching too aggressively for shorter utterances which should have matched children who had the shorter utterances etc.  The fix was to add explicit None utterances to the Dispatch model which were longer than the utterances in the children etc.  What is None in a child isn't exactly None on the parent, especially if you are in the middle of a dialog and you already have context so you are maybe running LUIS against that specific child model anyway.  It would be better to have the ability to explicitly add None utterances to the dispatch tool.  That way the user decides weather that is an aggregate per the proposal or something else.

**Comment by hansmbakker** [comment]
@tsuwandy @sgellock could you share what the status of this issue is, and what the current dispatch behavior is?

Is there any way, today, to automatically move `None` utterances from children to the parent Dispatch model?

**Comment by tsuwandy** [comment]
@hansmbakker, this is actually on the latest Dispatch CLI.   All the None intents from child LUIS apps are combined (after conflicts are resolved) into Dispatch app.  
@genbod, you could also be add explicit None intent to Dispatch.  Create a file with all the utterances for the Dispatch None add, add it to Dispatch as source with "--intentName None" parameter to the "dispatch add" command

**Comment by hansmbakker** [comment]
Using the Dispatch CLI I do not see the behavior that it generates a `None` intent based on the utterances in the child apps!

**Comment by tsuwandy** [comment]
@hansmbakker, do your child LUIS apps have specific utterances in their None intents?

**Comment by hansmbakker** [comment]
What do you mean with “specific”?

Yes, one or two of my LUIS apps have a None intent with utterances.

When I do `dispatch refresh` the None intent in my dispatch app is removed

**Comment by tsuwandy** [comment]
@hcyang is checking on this...  Will update this thread.

**Comment by tsuwandy** [comment]
@hansmbakker, we found a regression.  Working on the fix...

**Comment by tsuwandy** [comment]
@hansmbakker , latest version of Dispatch CLI with the fix for None intents is deployed.

**Comment by sgellock** [comment]
@hansmbakker this fix is in the newly published 1.3.0 version
