### ISSUE TITLE
QnAMaker-cli fails with "stderr maxBuffer exceeded"

### ISSUE THREAD

**Issue by sgellock** [Microsoft/botbuilder-tools#873]
## Tool
Name: QnAMaker
Version: *1.1.0*
OS: *macOS*

## Describe the bug
When running an `Msbot clone services` on the samples `bot.recipe` file, QnA Maker will fail with the following error:

Creating QnA Maker KB [qnamaker-QnAMaker]
`qnamaker create kb --subscriptionKey "my subscription key was removed" --name "qnamaker-QnAMaker" --in deploymentScripts/msbotClone/34.qna --wait --msbot -q`
**stderr maxBuffer exceeded**
 
## To Reproduce
1. cd into `samples/javascript_nodejs/11.qnamaker sample`
2. npm install
3. from a terminal, run `msbot clone services --name "bug-qnamaker-5" --code-dir "." --location westus --sdkLanguage "Node" --folder deploymentScripts/msbotClone –verbose`

## Expected behavior
qnamaker succeeds creating a kb from a model that was previously exported from the service

[bug]

**Comment by mdrichardson** [comment]
I came across this while trying to fix https://github.com/Microsoft/BotBuilder-Samples/issues/1187.

A possible fix might be changing a line in `function runCommand()` from `msbot-clone-services.ts` from:

```
let p = await exec(command);
```

to:

```
let p = await exec(command, { maxBuffer: 1024 * 2000 });
```

As I explain in my other, linked issue, I haven't been able to replicate this particular error very well, but the idea came from [this SO question](https://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process) and that's the line I believe it would belong. Other solutions recommended using `.spawn` instead of `.exec`, but that would require changing the `command` args from a [string as part of the command](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) to a [command and a list of string arguments](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options). I haven't tested this, but figured the links would help.

Personally, I'm moderately sure that this issue is linked to the one at the top of this comment--a major inconsistency in `qnamaker create kb`, as I got that error occasionally during testing.

**Comment by rokulka** [comment]
I've been using msclone for quite a number of times since I was debugging the other 'create kb' issue, I couldn't repro this issue.

As per node [docs](https://github.com/nodejs/node/blob/master/doc/api/child_process.md), default maxBuffer is 200KB. We can increase it as @mdrichardson  suggested.

@sgellock  Please let me know, i'll raise a PR.

**Comment by sgellock** [comment]
currently I use msbot clone services for all my deployment activities.  I run into the issue frequently enough that I'd like us to take a change.  thanks guys.
