### ISSUE TITLE
AZ CLI: Remove extra deployment files 

### ISSUE THREAD

**Issue by stevengum** [Microsoft/botbuilder-tools#908]
## Tool
Name: `az bot`

## Describe the problem
iisnode.yml and web.config files that aren't normally a part of the bot's checked-in source code (at the very least, they do not exist in our samples) are left over in the local folder after a `az bot publish`.

## Describe the solution you'd like
Remove the files after the zipped up source code is uploaded to Kudu.

[enhancement]

**Comment by navzam** [comment]
@stevengum az cli is version 2.0.55

But I just tried on a clean project and it did not leave behind the upload.zip. I think previously it was left behind on a publish that failed because one of the steps failed with something like "request took too long". So maybe it isn't cleaned up properly on a failed publish.

**Comment by stevengum** [comment]
Closing via Azure/Azure-cli#8420
