### ISSUE TITLE
`luis update version|application` silently ignores model changes other than rename

### ISSUE THREAD

**Issue by dkisselev** [Microsoft/botbuilder-tools#926]
## Tool
Name: LUIS

## Describe the problem
I'm using ludown to generate json models and trying to create a quick iterative flow such as: `ludown parse toluis... && luis update version --in...`

The `luis update version` command currently only supports updating the name or description of the version (as documented in the readme).

However, it accepts a complete json model file with `--in` and silently performs no operations with most of the file.

As a user, this is disorienting because I discovered the command by navigating the CLI's output, `luis import version` worked as expected, yet `luis update version` returned success but no changes were appearing in the portal.

## Describe the solution you'd like
The LUIS CLI & API should be able to handle full in-place replacement for versions & applications (#633).

In the mean time, the CLI (and possibly API) should return a warning that the submitted update request *only* changed the name/description because updating full versions is not implemented.

[enhancement]

**Comment by AmirGeorge** [comment]
Hi Denis,

The functionality to just update the name/ description of the application is by design. We outline that in the Readme to avoid the confusion.

Regarding your suggestion to display a warning, this is not conventional. Traditionally you can always send extra JSON properties in a request body and they would get silently dropped if the API does not need them. You wouldn't expect an API accepting a JSON payload to behave like that.
