### ISSUE TITLE
msbot creates an Application Insights resource and should configure it on the qnahost Web App

### ISSUE THREAD

**Issue by brisebois** [Microsoft/botbuilder-tools#988]
## Tool
Name: Msbot

## Describe the problem
msbot creates an Application Insights resource, but does not configure it on the **qnahost** Web App when using **msbot clone services** with the **Enterprise Bot Template**.

Installing and linking the Application Insights site extension to the Application Insights resource enables us to leverage [queries for analytics on our QnA Maker knowledge bases](https://docs.microsoft.com/en-us/azure/cognitive-services/QnAMaker/how-to/get-analytics-knowledge-base)

## Describe the solution you'd like
I would expect that the Application Insights site extension would be installed and configured on the **qnahost** Web App.

[enhancement]

**Comment by sgellock** [comment]
@brisebois, we will be releasing ARM template support for all provisioning and configuration activities for Bot Framework.  This will show up in all the samples, all our code generators, and documentation.  We will be deprecating the use of .recipe files, and msbot clone functionality once we release these updates.  

Since we are deprecating msbot as a provisioning and deployment option, replaced with ARM template support, I'm going to resolve this issue as "won't fix"
