### ISSUE TITLE
LUIS app containing patterns creates malformed JSON utterances in generated dispatch app

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/botbuilder-tools#991]
## Tool
Name: Dispatch
Version: 1.2.3
OS: Windows 10 build 17763

## Describe the bug
Having a LUIS app containing patterns creates malformed JSON utterances in generated dispatch app (see screenshot)

## To Reproduce
1. Set up LUIS app + Dispatch app in bot file
2. Make sure the LUIS app contains only "pattern utterances" and no "direct utterances"
2. Call `dispatch refresh -b "somebotfile.bot" --secret "SomeSecret"`
3. Inspect the utterances for the child LUIS app in the Dispatch app

## Expected behavior
Patterns are only copied to Dispatch app as Patterns

## Screenshots
![image](https://user-images.githubusercontent.com/3463496/53338656-89704700-3904-11e9-93ed-7eedaf7bb6e8.png)

## Additional context

[bug]

**Comment by Zerryth** [comment]
@hansmbakker I tried going down the path of repro-ing this issue, but unfortunately 2 other issues are hindering me from getting a dispatch model created, to even get to the point of trying to `dispatch refresh`:

1. Having problems with `dispatch create` command not creating (issue https://github.com/Microsoft/botbuilder-tools/issues/563#issuecomment-467168661)
  * for this current GH issue you posted, I created my child LUIS model that has patterns only (no utterances in the intent)
  * added it to `.dispatch` file
  * but when I try `dispatch create`-ing, it doesn't create (`ERROR
Invalid pattern hello [unicorn]`)
  * or try `dispatch create | msbot connect dispatch --stdin` it gives `[msbot] TypeError [ERR_INVALID_URL]: Invalid URL:
[msbot] Usage: msbot connect dispatch [options]`
2. Can't even go the round about way of using `msbot clone` in the `14.nlp-with-dispatch` sample, because of malforming `.bot` files when running the command: #997 

Once I can make an actual dispatch model--with or without adding patterns, I'll dig into trying to repro this issue further

**Comment by tsuwandy** [comment]
@hansmbakker, do you mind sharing your LUIS app (exported as json file)? You could email it to tiens@microsoft.com.  

I assume you have a dispatch with only 1 app?  Trying to figure out how to get a repro.  Thanks!

**Comment by hansmbakker** [comment]
@tsuwandy although I tried a lot, unfortunately I cannot reproduce the “patterns JSON appearing as utterances” scenario in a blank environment ☹ however I can reproduce it in a running environment. Would sharing my screen help?

**Comment by tsuwandy** [comment]
@hansmbakker , sorry for the delay.  I'm going to close this as we couldn't repro.  Please let me know if you have some time to share your screen, feel free to send invite to tiens.suwandy@microsoft.com when you get a chance.  Thank you!

**Comment by hansmbakker** [comment]
I have not run into the issue for some time now; I'm using a `.dispatch` configuration file now to refresh my Dispatch app.

Thank you for the offer, if I run into the issue again I'll let you know!
